#!/usr/bin/env node
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { definitions, validate, check } = require('../music-composition-studio/lib/contracts');
const { hash } = require('../music-composition-studio/lib/canonical');
const { MusicLedger } = require('../music-composition-studio/lib/ledger');
const { MockMusicProvider, HttpMusicProvider, enforceBudget, pollControlled, providerCatalog } = require('../music-composition-studio/lib/providers');
const { compositionDna } = require('../music-composition-studio/lib/compatibility');
const { invalidationPlan } = require('../music-composition-studio/lib/invalidation');
const { renderFixture } = require('../music-composition-studio/services/audio-service');
const { baseRequest, runProduction, buildConstitution, selectiveReprocess } = require('../music-composition-studio/pipeline');
const { organizerInput, workflowOutput } = require('../music-composition-studio/adapters');
const { handleError } = require('../music-composition-studio/error-handler');

async function main() {
  assert.strictEqual(Object.keys(definitions).length, 23, 'all requested contracts must exist');
  for (const [name, schema] of Object.entries(definitions)) { assert.strictEqual(schema.additionalProperties, false, `${name} root must be closed`); check(schema, schema.examples[0]); assert.throws(() => check(schema, schema['x-invalid-examples'][0]), `${name} invalid example must fail`); }
  const request = baseRequest(); validate('musicProductionRequest', request); assert.throws(() => validate('musicProductionRequest', { ...request, unknown: true }), /not allowed/); assert.strictEqual(hash({ a: 1, b: 2 }), hash({ b: 2, a: 1 }));
  assert.strictEqual(organizerInput({ music_production_request: request }).production_id, request.production_id);
  const ledger = new MusicLedger(); ledger.begin({ ...request, composition_id: 'CMP-1' }); const first = ledger.upsertJob({ composition_id: 'CMP-1', module: 'MSC-50', component_id: 'bass', revision: 1, input_hash: 'same', status: 'QUEUED' }); ledger.completeJob(first.job_key, { uri: 'storage://bass.wav' }); const repeat = ledger.upsertJob({ composition_id: 'CMP-1', module: 'MSC-50', component_id: 'bass', revision: 1, input_hash: 'same', status: 'QUEUED' }); assert.strictEqual(repeat.reused, true); assert.strictEqual(ledger.recordCallback({ provider: 'mock', provider_request_id: 'abc', payload: {} }).duplicate, false); assert.strictEqual(ledger.recordCallback({ provider: 'mock', provider_request_id: 'abc', payload: {} }).duplicate, true);
  const mock = new MockMusicProvider(); const submitted = await mock.submit({ input_hash: 'x', module: 'MSC-10', component_id: 'x', dry_run: true, provider_policy: { mode: 'mock' } }); assert.strictEqual((await pollControlled({ provider: mock, request_id: submitted.request_id, maxAttempts: 1, sleep: async () => {} })).status, 'COMPLETED'); await assert.rejects(() => new HttpMusicProvider({}).submit({ input_hash: 'x', dry_run: true, provider_policy: { mode: 'mock' } }), /disabled/); assert.ok(providerCatalog().mastering_provider.mock); assert.throws(() => enforceBudget({ budget_limits: { max_cost: 0 } }, 1), /BUDGET_EXCEEDED/);
  const audio = renderFixture({ outputDir: fs.mkdtempSync(path.join(os.tmpdir(), 'msc-audio-')), kind: 'test', compositionId: 'CMP-1', seconds: 1 }); assert.ok(fs.existsSync(audio.path)); assert.strictEqual(fs.readFileSync(audio.path).subarray(0, 4).toString(), 'RIFF'); assert.strictEqual(audio.binary_in_control_plane, false);
  const fast = await runProduction(baseRequest({ production_id: 'MSC-TEST-FAST' })); const standard = await runProduction(baseRequest({ production_id: 'MSC-TEST-STANDARD', production_tier: 'STANDARD', brief: { ...request.brief, duration_target_seconds: 75 } })); const premium = await runProduction(baseRequest({ production_id: 'MSC-TEST-PREMIUM', production_tier: 'PREMIUM', brief: { ...request.brief, duration_target_seconds: 120, voice_requested: true }, voice_consent: { status: 'GRANTED', voice_id: 'synthetic-test-voice' } }));
  for (const result of [fast, standard, premium]) { assert.strictEqual(result.music_package.status, 'READY'); assert.ok(result.composition_dna.length >= 2); assert.ok(result.song_animatic.uri.startsWith('file://')); assert.ok(result.stem_jobs.length); assert.strictEqual(result.music_package.costs.total, 0); assert.ok(result.transitions.includes('READY')); }
  assert.strictEqual(workflowOutput(fast.music_package).publish_requested, false);
  const error = handleError({ workflow: 'MSC-99', node: 'test', production_id: 'MSC-1', payload: { token: 'sensitive' } }, new Error('BUDGET_EXCEEDED token=hidden')); assert.strictEqual(error.error_code, 'BUDGET_EXCEEDED'); assert.ok(error.cancel); assert.ok(error.message.includes('[REDACTED]'));
  assert.ok(premium.vocal_manifest.artifacts.length); assert.ok(standard.stem_jobs.length > fast.stem_jobs.length); assert.strictEqual(fast.music_package.deliverables.stems.some((uri) => uri.includes('base64')), false);
  const blocked = await runProduction(baseRequest({ production_id: 'MSC-TEST-SIMILAR', brief: { ...request.brief, purpose: 'Copy exactly a recognizable artist melody' } })); assert.strictEqual(blocked.music_package.status, 'FAILED'); assert.ok(blocked.qa_report.blocking_issues.includes('SIMILARITY_BLOCK')); await assert.rejects(() => runProduction(baseRequest({ production_id: 'MSC-TEST-CONSENT', brief: { ...request.brief, voice_requested: true }, voice_consent: { status: 'DENIED', voice_id: 'x' } })), /AUTHORIZATION_ERROR/);
  assert.deepStrictEqual(invalidationPlan('metadata'), ['package']); assert.deepStrictEqual(invalidationPlan('bass_timbre'), ['bass', 'affected_sections', 'arrangement', 'mix', 'master', 'package']); assert.deepStrictEqual(invalidationPlan('loudness'), ['master', 'package']); assert.ok(invalidationPlan('chorus').includes('stems_chorus')); const revised = selectiveReprocess('constitution', fast.music_constitution); assert.strictEqual(revised.next_constitution.revision, 2); assert.deepStrictEqual(selectiveReprocess('metadata', fast.music_constitution).invalidated, ['package']);
  const dna = compositionDna({ candidates: fast.candidate_set, constitution: fast.music_constitution, topK: 2, beamWidth: 3 }); assert.ok(dna.length >= 2 && dna.length <= 3); const updated = buildConstitution({ ...fast.request, composition_id: fast.request.composition_id }, fast.reference_analyses, fast.music_constitution); assert.strictEqual(updated.revision, 2); assert.notStrictEqual(updated.lock_hash, fast.music_constitution.lock_hash);
  const migration = fs.readFileSync(path.join(__dirname, '..', 'db', 'migrations', '20260724_music_composition_studio.sql'), 'utf8'); for (const table of ['music_productions', 'music_constitutions', 'music_jobs', 'music_artifacts', 'music_dependencies', 'music_candidates', 'music_composition_dna', 'music_sections', 'music_stems', 'music_arrangements', 'music_mix_versions', 'music_master_versions', 'music_qa_reports', 'music_provider_events', 'music_cost_events', 'music_reference_analyses']) assert.ok(migration.includes(table)); assert.ok(!/\bdrop\b/i.test(migration));
  const generatedDir = path.join(__dirname, '..', 'generated-workflows', 'music-composition-studio'); const operational = fs.readdirSync(generatedDir).filter((file) => file.endsWith('.json') && file !== 'package.json'); assert.deepStrictEqual(operational, ['music-composition-studio.unified.json']); const unified = JSON.parse(fs.readFileSync(path.join(generatedDir, operational[0]), 'utf8')); assert.strictEqual(unified.active, false); assert.strictEqual(unified.nodes.some((node) => node.type === 'n8n-nodes-base.executeWorkflow'), false); assert.ok(unified.nodes.some((node) => node.name === 'MSC-90 Evaluation and Package')); const archive = fs.readdirSync(path.join(generatedDir, 'archive')).filter((file) => file.endsWith('.json')); assert.strictEqual(archive.length, 11);
  console.log('Music Composition Studio tests: OK');
}
main().catch((error) => { console.error(error.stack || error.message); process.exit(1); });
