#!/bin/bash

echo "🤖 WhatsApp Bot - Início Rápido"
echo "==============================="
echo ""
echo "✅ Repositório clonado com sucesso!"
echo "✅ Dependências instaladas!"
echo "✅ Bots configurados e prontos!"
echo ""
echo "📱 Para usar seu bot:"
echo ""
echo "1️⃣ Bot Básico (recomendado):"
echo "   node meu_bot.js"
echo ""
echo "2️⃣ Bot Avançado (mais recursos):"
echo "   node bot_avancado.js"
echo ""
echo "3️⃣ Exemplo oficial completo:"
echo "   node example.js"
echo ""
echo "📖 Documentação completa:"
echo "   cat README_MEU_BOT.md"
echo ""
echo "🔧 Configuração detalhada:"
echo "   cat CONFIGURACAO.md"
echo ""
echo "⚡ Comando rápido para iniciar:"
read -p "Pressione Enter para iniciar o bot básico ou Ctrl+C para sair..."

echo "🚀 Iniciando bot básico..."
node meu_bot.js
