-- Finance v1: additive, D1-compatible and owned exclusively by finance.
CREATE TABLE IF NOT EXISTS finance_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);
INSERT OR IGNORE INTO finance_settings(key, value, updated_at) VALUES ('module_enabled', 'false', CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS finance_scopes (
  id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('unit','personal')), unit_slug TEXT,
  label TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, currency TEXT NOT NULL DEFAULT 'BRL', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
  UNIQUE(kind, unit_slug), CHECK((kind='unit' AND unit_slug IS NOT NULL) OR (kind='personal' AND unit_slug IS NULL))
);
INSERT OR IGNORE INTO finance_scopes(id,kind,unit_slug,label,active,currency,created_at,updated_at) VALUES
 ('finance-scope-novo-hamburgo','unit','novo-hamburgo','Novo Hamburgo',1,'BRL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
 ('finance-scope-barra-shopping-sul','unit','barra-shopping-sul','BarraShoppingSul',1,'BRL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
 ('finance-scope-personal','personal',NULL,'Financeiro pessoal',0,'BRL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS finance_access_grants (id TEXT PRIMARY KEY, username TEXT NOT NULL, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), permission TEXT NOT NULL CHECK(permission IN ('viewer','operator','admin','auditor')), created_at TEXT NOT NULL, created_by TEXT, UNIQUE(username, scope_id));
CREATE TABLE IF NOT EXISTS finance_cost_centers (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(scope_id,name));
CREATE TABLE IF NOT EXISTS finance_ledger_accounts (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), code TEXT NOT NULL, name TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('asset','liability','equity','income','expense')), system_key TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, UNIQUE(scope_id,code), UNIQUE(scope_id,system_key));
CREATE TABLE IF NOT EXISTS finance_accounts (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), ledger_account_id TEXT NOT NULL REFERENCES finance_ledger_accounts(id), name TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('cash','bank','card','clearing')), currency TEXT NOT NULL DEFAULT 'BRL', opening_balance_minor INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(scope_id,name), UNIQUE(ledger_account_id));
CREATE TABLE IF NOT EXISTS finance_categories (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), ledger_account_id TEXT REFERENCES finance_ledger_accounts(id), parent_id TEXT REFERENCES finance_categories(id), name TEXT NOT NULL, direction TEXT NOT NULL CHECK(direction IN ('income','expense','both')), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(scope_id,parent_id,name));
CREATE TABLE IF NOT EXISTS finance_payees (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), name TEXT NOT NULL, name_key TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(scope_id,name_key));
CREATE TABLE IF NOT EXISTS finance_tags (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), name TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(scope_id,name));
CREATE TABLE IF NOT EXISTS finance_movements (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), type TEXT NOT NULL CHECK(type IN ('income','expense','transfer')), status TEXT NOT NULL CHECK(status IN ('draft','posted','cancelled')), account_id TEXT NOT NULL REFERENCES finance_accounts(id), destination_account_id TEXT REFERENCES finance_accounts(id), category_id TEXT REFERENCES finance_categories(id), payee_id TEXT REFERENCES finance_payees(id), cost_center_id TEXT REFERENCES finance_cost_centers(id), description TEXT NOT NULL, amount_minor INTEGER NOT NULL CHECK(amount_minor > 0), currency TEXT NOT NULL DEFAULT 'BRL', competence_date TEXT NOT NULL, due_date TEXT, paid_date TEXT, source TEXT NOT NULL DEFAULT 'manual', external_id TEXT, revision INTEGER NOT NULL DEFAULT 1, created_by TEXT NOT NULL, updated_by TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, cancelled_at TEXT, CHECK((type='transfer' AND destination_account_id IS NOT NULL AND destination_account_id != account_id) OR (type!='transfer' AND destination_account_id IS NULL)));
CREATE INDEX IF NOT EXISTS finance_movements_scope_period_idx ON finance_movements(scope_id, competence_date DESC) WHERE status != 'cancelled';
CREATE UNIQUE INDEX IF NOT EXISTS finance_movements_external_idx ON finance_movements(scope_id, source, external_id) WHERE external_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS finance_journal_entries (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), movement_id TEXT NOT NULL REFERENCES finance_movements(id), status TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(movement_id));
CREATE TABLE IF NOT EXISTS finance_journal_lines (id TEXT PRIMARY KEY, entry_id TEXT NOT NULL REFERENCES finance_journal_entries(id), ledger_account_id TEXT NOT NULL REFERENCES finance_ledger_accounts(id), direction TEXT NOT NULL CHECK(direction IN ('debit','credit')), amount_minor INTEGER NOT NULL CHECK(amount_minor > 0), currency TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS finance_installments (id TEXT PRIMARY KEY, movement_id TEXT NOT NULL REFERENCES finance_movements(id), sequence INTEGER NOT NULL CHECK(sequence > 0), due_date TEXT NOT NULL, amount_minor INTEGER NOT NULL CHECK(amount_minor > 0), paid_date TEXT, status TEXT NOT NULL CHECK(status IN ('open','paid','cancelled')), created_at TEXT NOT NULL, UNIQUE(movement_id,sequence));
CREATE TABLE IF NOT EXISTS finance_movement_tags (movement_id TEXT NOT NULL REFERENCES finance_movements(id), tag_id TEXT NOT NULL REFERENCES finance_tags(id), PRIMARY KEY(movement_id,tag_id));
CREATE TABLE IF NOT EXISTS finance_import_batches (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), filename TEXT NOT NULL, file_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('staged','committed','rejected')), mapping_json TEXT NOT NULL DEFAULT '{}', summary_json TEXT NOT NULL DEFAULT '{}', created_by TEXT NOT NULL, created_at TEXT NOT NULL, committed_at TEXT, UNIQUE(scope_id,file_hash));
CREATE TABLE IF NOT EXISTS finance_import_rows (id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES finance_import_batches(id), row_number INTEGER NOT NULL, raw_json TEXT NOT NULL, normalized_json TEXT, row_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('valid','invalid','exact_duplicate','possible_duplicate','committed')), error TEXT, movement_id TEXT REFERENCES finance_movements(id), UNIQUE(batch_id,row_number));
CREATE TABLE IF NOT EXISTS finance_import_duplicate_candidates (id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES finance_import_batches(id), row_id TEXT NOT NULL REFERENCES finance_import_rows(id), movement_id TEXT REFERENCES finance_movements(id), kind TEXT NOT NULL CHECK(kind IN ('exact','possible')), decision TEXT NOT NULL DEFAULT 'pending' CHECK(decision IN ('pending','accept','skip')), created_at TEXT NOT NULL, UNIQUE(row_id,movement_id,kind));
CREATE TABLE IF NOT EXISTS finance_reconciliation_lines (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), account_id TEXT NOT NULL REFERENCES finance_accounts(id), posted_date TEXT NOT NULL, amount_minor INTEGER NOT NULL, currency TEXT NOT NULL, description TEXT, external_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS finance_reconciliation_matches (id TEXT PRIMARY KEY, statement_line_id TEXT NOT NULL REFERENCES finance_reconciliation_lines(id), movement_id TEXT NOT NULL REFERENCES finance_movements(id), status TEXT NOT NULL CHECK(status IN ('suggested','confirmed','rejected')), created_by TEXT, created_at TEXT NOT NULL, UNIQUE(statement_line_id,movement_id));
CREATE TABLE IF NOT EXISTS finance_attachments (id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES finance_scopes(id), movement_id TEXT REFERENCES finance_movements(id), object_key TEXT NOT NULL, filename TEXT NOT NULL, content_type TEXT, size_bytes INTEGER, created_by TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS finance_idempotency_keys (key TEXT NOT NULL, actor TEXT NOT NULL, route TEXT NOT NULL, scope_id TEXT, request_hash TEXT NOT NULL, response_json TEXT NOT NULL, status_code INTEGER NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(key,actor,route));
CREATE TABLE IF NOT EXISTS finance_audit_events (id TEXT PRIMARY KEY, scope_id TEXT REFERENCES finance_scopes(id), actor TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, request_id TEXT, before_json TEXT, after_json TEXT, created_at TEXT NOT NULL);
