import { useState, useEffect, useRef } from 'react'
import { useKV } from '@/lib/spark-mock'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { toast } from 'sonner'
import {
  Bell,
  Warning,
  CheckCircle,
  X,
  Clock,
  TrendUp,
  TrendDown,
  Users,
  Target,
  CurrencyDollar,
  ChartBar,
  Pulse,
  Lightning
} from "@phosphor-icons/react"

interface PerformanceAlert {
  id: string
  type: 'performance' | 'threshold' | 'trend' | 'anomaly'
  severity: 'low' | 'medium' | 'high' | 'critical'
  title: string
  message: string
  metric: string
  currentValue: number
  expectedValue?: number
  threshold?: number
  timestamp: string
  acknowledged: boolean
  autoGenerated: boolean
  source: string
}

interface MetricThreshold {
  id: string
  metric: string
  name: string
  icon: string
  unit: string
  minValue?: number
  maxValue?: number
  warningThreshold: number
  criticalThreshold: number
  operator: 'above' | 'below'
  enabled: boolean
}

export function PerformanceAlerts() {
  const [alerts, setAlerts] = useKV<PerformanceAlert[]>('performance-alerts-system', [])
  const [thresholds, setThresholds] = useKV<MetricThreshold[]>('metric-thresholds', [
    {
      id: '1',
      metric: 'response_time',
      name: 'Tempo de Resposta',
      icon: 'clock',
      unit: 'ms',
      warningThreshold: 2000,
      criticalThreshold: 5000,
      operator: 'above',
      enabled: true
    },
    {
      id: '2',
      metric: 'conversion_rate',
      name: 'Taxa de Conversão',
      icon: 'target',
      unit: '%',
      warningThreshold: 20,
      criticalThreshold: 15,
      operator: 'below',
      enabled: true
    },
    {
      id: '3',
      metric: 'customer_satisfaction',
      name: 'Satisfação do Cliente',
      icon: 'users',
      unit: '/10',
      minValue: 0,
      maxValue: 10,
      warningThreshold: 7,
      criticalThreshold: 6,
      operator: 'below',
      enabled: true
    },
    {
      id: '4',
      metric: 'revenue_target',
      name: 'Meta de Receita',
      icon: 'dollar',
      unit: '%',
      warningThreshold: 80,
      criticalThreshold: 60,
      operator: 'below',
      enabled: true
    },
    {
      id: '5',
      metric: 'system_uptime',
      name: 'Uptime do Sistema',
      icon: 'activity',
      unit: '%',
      warningThreshold: 99,
      criticalThreshold: 95,
      operator: 'below',
      enabled: true
    }
  ])

  const [currentMetrics, setCurrentMetrics] = useState({
    response_time: 1850,
    conversion_rate: 18.5,
    customer_satisfaction: 6.2,
    revenue_target: 75,
    system_uptime: 98.7
  })

  const [filter, setFunnel] = useState<'all' | 'unacknowledged' | 'critical' | 'high'>('unacknowledged')
  const intervalRef = useRef<number | null>(null)

  // Simulate real-time metric monitoring
  useEffect(() => {
    intervalRef.current = window.setInterval(() => {
      // Simulate metric fluctuations
      setCurrentMetrics(prev => ({
        response_time: Math.max(500, prev.response_time + (Math.random() - 0.5) * 400),
        conversion_rate: Math.max(0, Math.min(100, prev.conversion_rate + (Math.random() - 0.5) * 4)),
        customer_satisfaction: Math.max(0, Math.min(10, prev.customer_satisfaction + (Math.random() - 0.5) * 0.8)),
        revenue_target: Math.max(0, Math.min(120, prev.revenue_target + (Math.random() - 0.5) * 6)),
        system_uptime: Math.max(90, Math.min(100, prev.system_uptime + (Math.random() - 0.5) * 1))
      }))
    }, 5000)

    return () => {
      if (intervalRef.current) window.clearInterval(intervalRef.current)
    }
  }, [])

  // CheckCircle thresholds and generate alerts
  useEffect(() => {
    thresholds.forEach(threshold => {
      if (!threshold.enabled) return

      const currentValue = currentMetrics[threshold.metric as keyof typeof currentMetrics]
      if (currentValue === undefined) return

      const shouldAlert = threshold.operator === 'above'
        ? currentValue > threshold.criticalThreshold || currentValue > threshold.warningThreshold
        : currentValue < threshold.criticalThreshold || currentValue < threshold.warningThreshold

      if (shouldAlert) {
        const severity = threshold.operator === 'above'
          ? currentValue > threshold.criticalThreshold ? 'critical' : 'high'
          : currentValue < threshold.criticalThreshold ? 'critical' : 'high'

        // CheckCircle if we already have a recent alert for this metric
        const recentAlert = alerts.find(alert =>
          alert.metric === threshold.metric &&
          !alert.acknowledged &&
          (Date.now() - new Date(alert.timestamp).getTime()) < 300000 // 5 minutes
        )

        if (!recentAlert) {
          generateAlert(threshold, currentValue, severity)
        }
      }
    })
  }, [currentMetrics, thresholds])

  const generateAlert = (threshold: MetricThreshold, currentValue: number, severity: 'high' | 'critical') => {
    const alert: PerformanceAlert = {
      id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
      type: 'threshold',
      severity,
      title: `${threshold.name} ${severity === 'critical' ? 'Crítico' : 'Atenção'}`,
      message: `${threshold.name} está ${threshold.operator === 'above' ? 'acima' : 'abaixo'} do limite ${severity === 'critical' ? 'crítico' : 'de alerta'}: ${currentValue}${threshold.unit}`,
      metric: threshold.metric,
      currentValue,
      threshold: severity === 'critical' ? threshold.criticalThreshold : threshold.warningThreshold,
      timestamp: new Date().toISOString(),
      acknowledged: false,
      autoGenerated: true,
      source: 'Sistema de Monitoramento'
    }

    setAlerts(prev => [alert, ...prev])

    // Show toast notification
    toast.error(`🚨 ${alert.title}`, {
      description: alert.message,
      action: {
        label: "Reconhecer",
        onClick: () => acknowledgeAlert(alert.id)
      }
    })
  }

  const acknowledgeAlert = (alertId: string) => {
    setAlerts(prev => prev.map(alert =>
      alert.id === alertId
        ? { ...alert, acknowledged: true }
        : alert
    ))
    toast.success("Alerta reconhecido")
  }

  const dismissAlert = (alertId: string) => {
    setAlerts(prev => prev.filter(alert => alert.id !== alertId))
    toast.success("Alerta removido")
  }

  const acknowledgeAllAlerts = () => {
    setAlerts(prev => prev.map(alert => ({ ...alert, acknowledged: true })))
    toast.success("Todos os alertas foram reconhecidos")
  }

  const getMetricIcon = (iconType: string) => {
    switch (iconType) {
      case 'clock': return <Clock className="h-4 w-4" />
      case 'target': return <Target className="h-4 w-4" />
      case 'users': return <Users className="h-4 w-4" />
      case 'dollar': return <CurrencyDollar className="h-4 w-4" />
      case 'activity': return <Pulse className="h-4 w-4" />
      default: return <ChartBar className="h-4 w-4" />
    }
  }

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'low': return 'bg-blue-100 text-blue-800 border-blue-200'
      case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-200'
      case 'high': return 'bg-orange-100 text-orange-800 border-orange-200'
      case 'critical': return 'bg-red-100 text-red-800 border-red-200'
      default: return 'bg-gray-100 text-gray-800 border-gray-200'
    }
  }

  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'critical': return <Warning className="h-4 w-4 text-red-500" />
      case 'high': return <Warning className="h-4 w-4 text-orange-500" />
      case 'medium': return <Warning className="h-4 w-4 text-yellow-500" />
      case 'low': return <CheckCircle className="h-4 w-4 text-blue-500" />
      default: return <CheckCircle className="h-4 w-4 text-gray-500" />
    }
  }

  const getMetricStatus = (threshold: MetricThreshold) => {
    const currentValue = currentMetrics[threshold.metric as keyof typeof currentMetrics]
    if (currentValue === undefined) return 'unknown'

    if (threshold.operator === 'above') {
      if (currentValue > threshold.criticalThreshold) return 'critical'
      if (currentValue > threshold.warningThreshold) return 'warning'
      return 'normal'
    } else {
      if (currentValue < threshold.criticalThreshold) return 'critical'
      if (currentValue < threshold.warningThreshold) return 'warning'
      return 'normal'
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'critical': return 'text-red-600 bg-red-50 border-red-200'
      case 'warning': return 'text-orange-600 bg-orange-50 border-orange-200'
      case 'normal': return 'text-green-600 bg-green-50 border-green-200'
      default: return 'text-gray-600 bg-gray-50 border-gray-200'
    }
  }

  const formatValue = (value: number, unit: string) => {
    if (unit === 'ms') return `${Math.round(value)}ms`
    if (unit === '%') return `${value.toFixed(1)}%`
    if (unit === '/10') return `${value.toFixed(1)}/10`
    return `${value.toFixed(1)}${unit}`
  }

  const filteredAlerts = alerts.filter(alert => {
    switch (filter) {
      case 'unacknowledged':
        return !alert.acknowledged
      case 'critical':
        return alert.severity === 'critical'
      case 'high':
        return alert.severity === 'high'
      default:
        return true
    }
  })

  const unacknowledgedCount = alerts.filter(alert => !alert.acknowledged).length
  const criticalCount = alerts.filter(alert => alert.severity === 'critical' && !alert.acknowledged).length

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold flex items-center space-x-2">
            <Lightning className="h-6 w-6 text-accent" />
            <span>Alertas de Performance</span>
            {unacknowledgedCount > 0 && (
              <Badge variant={criticalCount > 0 ? "destructive" : "secondary"} className="ml-2">
                {unacknowledgedCount}
              </Badge>
            )}
          </h2>
          <p className="text-muted-foreground">
            Monitoramento automático de métricas críticas em tempo real
          </p>
        </div>
        <div className="flex items-center space-x-2">
          <Select value={filter} onValueChange={(value: any) => setFunnel(value)}>
            <SelectTrigger className="w-48">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Todos os Alertas</SelectItem>
              <SelectItem value="unacknowledged">Não Reconhecidos</SelectItem>
              <SelectItem value="critical">Críticos</SelectItem>
              <SelectItem value="high">Alta Prioridade</SelectItem>
            </SelectContent>
          </Select>
          {unacknowledgedCount > 0 && (
            <Button onClick={acknowledgeAllAlerts} variant="outline">
              <CheckCircle className="h-4 w-4 mr-2" />
              Reconhecer Todos
            </Button>
          )}
        </div>
      </div>

      {/* Real-time Metrics Dashboard */}
      <Card className="glass-card">
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Pulse className="h-5 w-5" />
            <span>Métricas em Tempo Real</span>
          </CardTitle>
          <CardDescription>
            Status atual das métricas monitoradas automaticamente
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {thresholds.filter(t => t.enabled).map((threshold) => {
              const currentValue = currentMetrics[threshold.metric as keyof typeof currentMetrics]
              const status = getMetricStatus(threshold)

              return (
                <div key={threshold.id} className={`p-4 rounded-lg border ${getStatusColor(status)}`}>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center space-x-2">
                      {getMetricIcon(threshold.icon)}
                      <span className="font-medium">{threshold.name}</span>
                    </div>
                    <Badge className={getStatusColor(status)}>
                      {status}
                    </Badge>
                  </div>
                  <div className="space-y-1">
                    <div className="text-2xl font-bold">
                      {formatValue(currentValue, threshold.unit)}
                    </div>
                    <div className="text-sm text-muted-foreground">
                      <div>Alerta: {formatValue(threshold.warningThreshold, threshold.unit)}</div>
                      <div>Crítico: {formatValue(threshold.criticalThreshold, threshold.unit)}</div>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* Active Alerts */}
      <Card className="glass-card">
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Bell className="h-5 w-5" />
            <span>Alertas Ativos</span>
          </CardTitle>
          <CardDescription>
            Alertas gerados automaticamente pelo sistema de monitoramento
          </CardDescription>
        </CardHeader>
        <CardContent>
          {filteredAlerts.length > 0 ? (
            <div className="space-y-4">
              {filteredAlerts.map((alert) => (
                <div key={alert.id} className={`border rounded-lg p-4 ${alert.acknowledged ? 'opacity-60' : ''}`}>
                  <div className="flex items-start justify-between">
                    <div className="flex items-start space-x-3">
                      {getSeverityIcon(alert.severity)}
                      <div className="flex-1 space-y-2">
                        <div className="flex items-center space-x-2">
                          <h4 className="font-medium">{alert.title}</h4>
                          <Badge className={getSeverityColor(alert.severity)}>
                            {alert.severity.toUpperCase()}
                          </Badge>
                          {alert.autoGenerated && (
                            <Badge variant="outline">
                              Auto
                            </Badge>
                          )}
                        </div>
                        <p className="text-sm text-muted-foreground">{alert.message}</p>
                        <div className="flex items-center space-x-4 text-xs text-muted-foreground">
                          <span>Métrica: {alert.metric}</span>
                          <span>Valor: {formatValue(alert.currentValue,
                            thresholds.find(t => t.metric === alert.metric)?.unit || '')}</span>
                          <span>Origem: {alert.source}</span>
                          <span>{new Date(alert.timestamp).toLocaleString()}</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      {!alert.acknowledged && (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => acknowledgeAlert(alert.id)}
                        >
                          <CheckCircle className="h-4 w-4 mr-1" />
                          Reconhecer
                        </Button>
                      )}
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => dismissAlert(alert.id)}
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-12">
              <CheckCircle className="h-12 w-12 text-green-500 mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">
                {filter === 'all' ? 'Nenhum alerta' : 'Todos os alertas reconhecidos'}
              </h3>
              <p className="text-muted-foreground">
                {filter === 'all'
                  ? 'Sistema operando dentro dos parâmetros normais'
                  : `Não há alertas ${filter === 'unacknowledged' ? 'pendentes' : filter === 'critical' ? 'críticos' : 'de alta prioridade'} no momento`
                }
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Threshold Configuration Summary */}
      <Card className="glass-card">
        <CardHeader>
          <CardTitle>Configuração de Limites</CardTitle>
          <CardDescription>
            Limites configurados para geração automática de alertas
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {thresholds.map((threshold) => (
              <div key={threshold.id} className="flex items-center justify-between p-3 border rounded-lg">
                <div className="flex items-center space-x-3">
                  {getMetricIcon(threshold.icon)}
                  <div>
                    <span className="font-medium">{threshold.name}</span>
                    <div className="text-sm text-muted-foreground">
                      Alerta: {threshold.operator} {formatValue(threshold.warningThreshold, threshold.unit)} |
                      Crítico: {threshold.operator} {formatValue(threshold.criticalThreshold, threshold.unit)}
                    </div>
                  </div>
                </div>
                <Badge variant={threshold.enabled ? "default" : "secondary"}>
                  {threshold.enabled ? "Ativo" : "Inativo"}
                </Badge>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
