const GLOBAL_STATES = ['RECEIVED', 'VALIDATING', 'GROUNDING', 'FOUNDATION_LOCKED', 'STRATEGIZING', 'CONSTITUTION_LOCKED', 'PREPRODUCTION', 'BLUEPRINT_LOCKED', 'STORYBOARD_READY', 'ASSETS_GENERATING', 'ASSETS_READY', 'SCENES_COMPOSING', 'SCENES_COMPOSED', 'SCENES_ANIMATING', 'SCENES_ANIMATED', 'ROUGH_CUT_READY', 'PICTURE_LOCKED', 'FINALIZING', 'QA', 'READY_TO_PUBLISH', 'NEEDS_REVIEW', 'FAILED'];
const JOB_STATES = ['PENDING', 'READY', 'RUNNING', 'WAITING_PROVIDER', 'DONE', 'FAILED_RETRYABLE', 'FAILED_BLOCKING', 'INVALIDATED', 'SKIPPED'];
const PROVIDER_STATES = ['SUBMITTED', 'PROCESSING', 'COMPLETED', 'FAILED_RETRYABLE', 'FAILED_BLOCKING', 'CANCELLED'];
module.exports = { GLOBAL_STATES, JOB_STATES, PROVIDER_STATES };
