import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

function assertNoDynamicShell(relative) {
  const text = read(relative)
  assert.doesNotMatch(text, /^\s*(?:source|\.)\s+[^\n]+/m, `${relative} must not load an env file as shell code`)
  assert.doesNotMatch(text, /^\s*eval\s+/m, `${relative} must not evaluate data as shell`)
  assert.doesNotMatch(text, /^\s*(?:exec\s+)?bash\s+-c\b/m, `${relative} must not create a shell command string`)
}

function sqlHeredocs(script, relative) {
  const heredocs = [...script.matchAll(/<<SQL\r?\n([\s\S]*?)\r?\nSQL/g)].map((match) => match[1])
  assert.ok(heredocs.length > 0, `${relative} must contain SQL heredocs covered by this regression`)
  return heredocs
}

test('isolated Clientes unit starts only the dedicated read-only entrypoint', () => {
  const unit = read('ops/runtime/units/crm-atendimento-production.service')
  assert.match(unit, /Description=.*Clientes.*read-only/)
  assert.match(unit, /EnvironmentFile=-__CONFIG_ROOT__\/crm-clientes-production-readonly\.env/)
  assert.match(unit, /UnsetEnvironment=.*NODE_OPTIONS.*LD_PRELOAD/)
  assert.match(unit, /Environment=CRM_DOMAIN=atendimento/)
  assert.match(unit, /Environment=CRM_ATENDIMENTO_READ_ONLY=true/)
  assert.match(unit, /Environment=CRM_ATENDIMENTO_COMMERCIAL_WRITES_ENABLED=false/)
  assert.match(unit, /Environment=HARMONIA_WORKER_ENABLED=false/)
  assert.match(unit, /ExecStart=\/usr\/bin\/node __REPO_ROOT__\/crm\/api\/server\/atendimentoRuntime\.js/)
  assert.doesNotMatch(unit, /ExecStart=.*server\.js/)
  assert.doesNotMatch(unit, /ExecStart=.*bash/)
  assert.doesNotMatch(unit, /crm\.service/)
})

test('dedicated runtime cannot import the shared HTTP process or a worker', () => {
  const runtime = read('crm/api/server/atendimentoRuntime.js')
  assert.match(runtime, /createIsolatedAtendimentoRuntime/)
  assert.match(runtime, /\/internal\/readiness/)
  assert.match(runtime, /app\.get\('\/internal\/readiness', limitInternal/)
  assert.match(runtime, /app\.get\('\/internal\/metrics', limitInternal/)
  assert.match(runtime, /INTERNAL_RATE_LIMIT_MAX_REQUESTS = 60/)
  assert.match(runtime, /READ_ONLY_RUNTIME/)
  assert.doesNotMatch(runtime, /from '\.\/server\.js'/)
  assert.doesNotMatch(runtime, /from ['"].*\/workers\//)
  assert.doesNotMatch(runtime, /from ['"].*harmonia\/worker/)
})

test('native scripts parse fixed configuration without dynamic shell evaluation', () => {
  for (const relative of [
    'scripts/run-atendimento-staging-migration.sh',
    'scripts/lockdown-atendimento-staging-runtime.sh',
    'scripts/refresh-atendimento-staging-quality.sh',
    'scripts/backup-atendimento-staging.sh',
    'scripts/provision-atendimento-staging.sh',
    'scripts/set-atendimento-staging-control.sh',
    'scripts/runtime/prepare-atendimento-staging-release.sh',
    'scripts/runtime/add-atendimento-staging-tunnel-route.sh',
    'scripts/runtime/install-atendimento-staging-service.sh',
    'scripts/runtime/rollback-atendimento-staging.sh',
    'scripts/provision-atendimento-production-readonly.sh',
    'scripts/lockdown-atendimento-production-runtime.sh',
    'scripts/set-atendimento-production-readonly-control.sh',
    'scripts/runtime/install-atendimento-production-service.sh',
    'scripts/runtime/install-atendimento-production-tunnel.sh',
    'scripts/runtime/route-atendimento-production-dns.sh',
    'scripts/runtime/prepare-atendimento-production-release.sh',
    'scripts/runtime/rollback-atendimento-production.sh',
    'scripts/validate-atendimento-staging-readonly.sh',
    'scripts/validate-atendimento-production-readonly.sh',
  ]) assertNoDynamicShell(relative)

  const migration = read('crm/api/scripts/run-atendimento-staging-migration.mjs')
  const stagingMigration = read('scripts/run-atendimento-staging-migration.sh')
  assert.match(migration, /MIGRATOR_ENV_FILE = '\/etc\/skincos\/crm-atendimento-staging-migrator\.env'/)
  assert.match(migration, /readLiteralEnvironment/)
  assert.doesNotMatch(migration, /process\.env\.DATABASE_URL/)
  assert.match(migration, /parseAtendimentoStagingMigrationInvocation/)
  assert.doesNotMatch(migration, /SKINCOS_ATENDIMENTO_STAGING_RELEASE_SHA/)
  assert.match(stagingMigration, /--release-sha/)
  assert.match(stagingMigration, /\/opt\/skincos\/releases\/\$RELEASE_SHA\/source/)
  assert.match(stagingMigration, /validate-atendimento-release\.mjs/)
  assert.match(stagingMigration, /--release-sha "\$RELEASE_SHA" --target staging/)
  assert.match(stagingMigration, /run_sudo_clean \/usr\/bin\/test -f "\$RUNNER"/)
  assert.doesNotMatch(stagingMigration, /ROOT_DIR=.*BASH_SOURCE/)

  const qualityRefresh = read('crm/api/scripts/run-atendimento-staging-quality-refresh.mjs')
  assert.match(qualityRefresh, /MIGRATOR_ENV_FILE = '\/etc\/skincos\/crm-atendimento-staging-migrator\.env'/)
  assert.match(qualityRefresh, /readLiteralEnvironment/)
  assert.doesNotMatch(qualityRefresh, /process\.env\.DATABASE_URL\s*\|\|/)
})

test('staging release, control and application role remain fixed and read-only', () => {
  const release = read('scripts/runtime/prepare-atendimento-staging-release.sh')
  const provision = read('scripts/provision-atendimento-staging.sh')
  const control = read('scripts/set-atendimento-staging-control.sh')
  const backup = read('scripts/backup-atendimento-staging.sh')
  const stagingMigration = read('scripts/run-atendimento-staging-migration.sh')
  const migrationRunner = read('crm/api/scripts/migrate-atendimento-staging.mjs')
  const qualityRefresh = read('crm/api/scripts/refresh-commercial-data-quality-staging.mjs')
  const harmoniaMigration = read('crm/api/scripts/migrate-harmonia-schema.mjs')
  const pgPool = read('crm/api/server/harmonia/store/pg.js')
  const ciSmoke = read('.github/workflows/ci-smoke.yml')
  const domainOnlyMigrationCli = [
    ['crm/api/scripts/migrate-clinical-approval.mjs', 'CLINICAL_APPROVAL_STAGING_REQUIRES_CONTROLLED_RUNNER'],
    ['crm/api/scripts/migrate-atendimento-commercial-analytics.mjs', 'COMMERCIAL_ANALYTICS_STAGING_REQUIRES_CONTROLLED_RUNNER'],
    ['crm/api/scripts/migrate-atendimento-commercial-operations.mjs', 'COMMERCIAL_OPERATIONS_STAGING_REQUIRES_CONTROLLED_RUNNER'],
    ['crm/api/scripts/migrate-atendimento-commercial-assisted-whatsapp.mjs', 'COMMERCIAL_ASSISTED_STAGING_REQUIRES_CONTROLLED_RUNNER'],
  ]
  const lockdown = read('scripts/lockdown-atendimento-staging-runtime.sh')
  const installer = read('scripts/runtime/install-atendimento-staging-service.sh')
  const rollback = read('scripts/runtime/rollback-atendimento-staging.sh')
  const rollbackControl = read('crm/api/scripts/validate-atendimento-staging-rollback-control.mjs')
  const unit = read('ops/runtime/units/crm-atendimento-staging.service')
  const retiredTunnel = read('scripts/runtime/add-atendimento-staging-tunnel-route.sh')

  assert.match(release, /readonly RELEASE_BASE='\/opt\/skincos\/releases'/)
  assert.match(release, /readonly NPM_CACHE='\/var\/lib\/skincos-runtime\/cache\/crm-api'/)
  assert.match(release, /^#!\/usr\/bin\/bash -p/m)
  assert.match(release, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(release, /run_sudo_clean\(\)/)
  assert.match(release, /run_skincos_npm\(\)/)
  assert.match(release, /git_clean\(\)/)
  assert.match(release, /resolve_checkout_git_dir\(\)/)
  assert.match(release, /readonly VERIFIED_GIT_DIR="\$\(resolve_checkout_git_dir\)"/)
  assert.match(release, /"GIT_DIR=\$VERIFIED_GIT_DIR" "GIT_WORK_TREE=\$ROOT_DIR"/)
  assert.match(release, /\/usr\/bin\/env -i/)
  assert.match(release, /\/usr\/bin\/git -c "safe\.directory=\$ROOT_DIR"/)
  assert.match(release, /git_clean archive --format=tar/)
  assert.match(release, /run_sudo_clean \/usr\/bin\/tar/)
  assert.match(release, /run_skincos_npm --prefix/)
  assert.match(release, /assert_release_targets\(\)/)
  assert.match(release, /--predecessor-sha/)
  assert.match(release, /Release SHA must equal the fetched origin\/main commit/)
  assert.match(release, /merge-base --is-ancestor/)
  assert.match(release, /\.skincos-release-lineage\.json/)
  assert.match(release, /run_sudo_clean \/usr\/bin\/rm -rf -- "\$STAGING"/)
  assert.doesNotMatch(release, /SKINCOS_RELEASE_BASE|CRM_NPM_CACHE/)
  assert.doesNotMatch(release, /^#!\/usr\/bin\/env bash/m)
  assert.doesNotMatch(release, /command -v git|command -v npm/)

  assert.match(provision, /readonly CONTROL_DIR="\$CONFIG_DIR\/atendimento-staging"/)
  assert.match(provision, /readonly SERVICE='crm-atendimento-staging\.service'/)
  assert.match(provision, /Staging provisioning requires the isolated runtime to be inactive/)
  assert.match(provision, /run_postgres_clean\(\)/)
  assert.match(provision, /random_hex\(\)/)
  assert.match(provision, /\\set app_password/)
  assert.doesNotMatch(provision, /--set=app_password|--set=migrator_password/)
  const provisionSql = sqlHeredocs(provision, 'scripts/provision-atendimento-staging.sh')
  assert.equal(provisionSql.length, 2, 'staging provision must keep both SQL payloads under regression coverage')
  for (const sql of provisionSql) {
    assert.doesNotMatch(sql, /^\s*#/m, 'PostgreSQL heredocs must use SQL comments, never shell # comments')
  }
  assert.match(provisionSql[0], /rolconnlimit/)
  assert.match(provisionSql[1], /alter role \$MIGRATOR_ROLE connection limit 3;/)
  assert.match(provisionSql[1], /^-- The isolated application has no safe direct Caixa projection yet\. Do not$/m)
  assert.match(provision, /readonly BACKUP_ROOT='\/var\/backups\/skincos\/clientes\/staging-control'/)
  assert.match(provision, /ATENDIMENTO_READINESS_TOKEN=\$readiness_token/)
  assert.match(provision, /"state":"maintenance"/)
  assert.match(provision, /"readOnly":true,"commercialContactWritesEnabled":false,"syntheticOnly":true/)
  assert.match(provision, /alter role \$APP_ROLE set default_transaction_read_only = on/)
  assert.match(provision, /revoke all privileges on database \$DB_NAME from \$APP_ROLE/)
  assert.match(provision, /revoke all privileges on all tables in schema crm_atendimento, crm_caixa, crm_sessions, harmonia from \$APP_ROLE/)
  assert.match(provision, /revoke all privileges on all sequences in schema crm_atendimento, crm_caixa, crm_sessions, harmonia from \$APP_ROLE/)
  assert.match(provision, /grant select on all tables in schema crm_atendimento, crm_sessions to \$APP_ROLE/)
  assert.doesNotMatch(provision, /grant select on all tables in schema [^\n]*crm_caixa to \$APP_ROLE/)
  assert.match(provision, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(provision, /mktemp \/tmp\/atendimento-staging-app-env\.XXXXXX/)
  assert.match(provision, /mktemp \/tmp\/atendimento-staging-migrator-env\.XXXXXX/)
  assert.match(provision, /mktemp \/tmp\/atendimento-staging-control\.XXXXXX/)
  assert.doesNotMatch(provision, /grant select on all tables in schema [^\n]*harmonia to \$APP_ROLE/)
  assert.doesNotMatch(provision, /grant select, insert, update, delete on all tables in schema [^\n]+ to \$APP_ROLE/)
  assert.doesNotMatch(provision, /grant usage, select, update on all sequences in schema [^\n]+ to \$APP_ROLE/)
  assert.doesNotMatch(provision, /CRM_API_PORT=8109/)

  assert.match(stagingMigration, /RUNTIME_GRANT_LOCKDOWN="\$RELEASE_ROOT\/scripts\/lockdown-atendimento-staging-runtime\.sh"/)
  assert.match(stagingMigration, /BACKUP_SCRIPT="\$RELEASE_ROOT\/scripts\/backup-atendimento-staging\.sh"/)
  assert.match(stagingMigration, /Fixed staging backup helper is unavailable in the immutable release/)
  assert.match(stagingMigration, /run_sudo_clean \/usr\/bin\/bash -p "\$RUNTIME_GRANT_LOCKDOWN" --apply/)
  assert.match(stagingMigration, /\/usr\/bin\/env -i "PATH=\$SAFE_PATH"/)
  assert.match(stagingMigration, /Staging migration requires maintenance control state/)
  assert.match(stagingMigration, /\/usr\/bin\/systemctl is-active --quiet "\$SERVICE"/)
  assert.match(stagingMigration, /run_sudo_clean \/usr\/bin\/bash -p "\$RUNTIME_GRANT_LOCKDOWN" --dry-run >\/dev\/null/)
  assert.match(stagingMigration, /backup_report="\$\(run_sudo_clean \/usr\/bin\/bash -p "\$BACKUP_SCRIPT"\)"/)
  assert.match(stagingMigration, /backup_created=true\\ database=skincos_staging\\ sha256=\[0-9a-f\]\{64\}\\ private=true\\ unique=true/)
  assert.ok(stagingMigration.indexOf('backup_report=') < stagingMigration.lastIndexOf('run_sudo_clean /usr/bin/node "$RUNNER"'))
  assert.match(stagingMigration, /run_sudo_clean \/usr\/bin\/node "\$RUNNER" "\$ACTION" --release-sha "\$RELEASE_SHA"/)
  assert.match(stagingMigration, /LOCKDOWN_REQUIRED=1/)
  assert.match(stagingMigration, /trap seal_staging_runtime_grants EXIT/)
  assert.match(stagingMigration, /trap 'exit 129' HUP/)
  assert.match(stagingMigration, /trap 'exit 130' INT/)
  assert.match(stagingMigration, /trap 'exit 143' TERM/)
  assert.match(stagingMigration, /trap '' HUP INT TERM/)
  assert.match(stagingMigration, /keeping the isolated service ineligible/)
  assert.match(migrationRunner, /ATENDIMENTO_STAGING_MIGRATOR_CONNECTION_LIMIT/)
  assert.match(migrationRunner, /ATENDIMENTO_STAGING_MIGRATION_POOL_MAX/)
  assert.match(migrationRunner, /createPool\(normalizedUrl, \{ max: ATENDIMENTO_STAGING_MIGRATION_POOL_MAX \}\)/)
  assert.match(migrationRunner, /assertAtendimentoStagingMigratorConnectionLimit\(lockClient\)/)
  assert.match(migrationRunner, /ATENDIMENTO_STAGING_OPTIONAL_COMMERCIAL_MIGRATION_RULES/)
  assert.match(migrationRunner, /parseAtendimentoStagingMigrationInvocation/)
  assert.match(migrationRunner, /COMMERCIAL_OPERATIONS_PREREQUISITES_MISSING/)
  assert.match(migrationRunner, /COMMERCIAL_ANALYTICS_MIGRATION_PREREQUISITES_MISSING/)
  assert.match(migrationRunner, /COMMERCIAL_ASSISTED_MIGRATION_PREREQUISITES_MISSING/)
  assert.doesNotMatch(migrationRunner, /COMMERCIAL_CANARY_MIGRATION_PREREQUISITES_MISSING/)
  assert.match(migrationRunner, /crm_atendimento\.staging_migration_evidence/)
  assert.match(migrationRunner, /set local lock_timeout = '3s'/)
  assert.match(migrationRunner, /set local statement_timeout = '60s'/)
  assert.match(migrationRunner, /schemaMigrationRecorded: false/)
  assert.match(migrationRunner, /STAGING_OPTIONAL_MIGRATION_DEFERRED_NOT_APPLIED/)
  assert.match(migrationRunner, /STAGING_OPTIONAL_MIGRATION_ROLLBACK_STATE_UNKNOWN/)
  assert.match(migrationRunner, /revoke all privileges on table \$\{STAGING_MIGRATION_EVIDENCE_RELATION\} from skincos_staging_crm_app/)
  assert.doesNotMatch(migrationRunner, /SKINCOS_ATENDIMENTO_STAGING_RELEASE_SHA/)
  assert.match(qualityRefresh, /ATENDIMENTO_STAGING_QUALITY_REFRESH_POOL_MAX/)
  assert.match(qualityRefresh, /acquireAtendimentoStagingMutationLock\(lockClient, 'ATENDIMENTO_STAGING_QUALITY_LOCK_UNAVAILABLE'\)/)
  assert.match(qualityRefresh, /assertAtendimentoStagingMigratorConnectionLimit\(lockClient\)/)
  assert.ok(qualityRefresh.lastIndexOf('acquireAtendimentoStagingMutationLock') < qualityRefresh.indexOf(').refresh('))
  assert.match(harmoniaMigration, /target === 'staging' \? \{ max: HARMONIA_STAGING_MIGRATION_POOL_MAX \} : undefined/)
  assert.match(harmoniaMigration, /acquireAtendimentoStagingMutationLock\(client, 'HARMONIA_STAGING_MIGRATION_LOCK_UNAVAILABLE'\)/)
  assert.match(harmoniaMigration, /assertAtendimentoStagingMigratorConnectionLimit\(client\)/)
  assert.ok(harmoniaMigration.lastIndexOf('acquireAtendimentoStagingMutationLock') < harmoniaMigration.indexOf("await client.query('begin')"))
  assert.match(pgPool, /export function createPgPool\(databaseUrl, options = \{\}\)/)
  assert.match(pgPool, /const max = Number\(options\?\.max \?\? 10\)/)
  assert.match(pgPool, /max,\r?\n/)
  assert.match(ciSmoke, /clientes_runtime_contract="\$\(changed scripts crm\/api ops\/runtime\/units\)"/)
  assert.match(ciSmoke, /node --test scripts\/tests\/clientes-production-readonly-runtime\.test\.mjs/)
  for (const [relative, code] of domainOnlyMigrationCli) {
    const cli = read(relative)
    assert.match(cli, new RegExp(`if \\(.*ATENDIMENTO_MIGRATION_TARGETS\\.STAGING.*\\)[\\s\\S]{0,180}${code}`), `${relative} must reject staging before creating a pool`)
    assert.ok(cli.indexOf(code) < cli.indexOf('pool = createPgPool(databaseUrl)'), `${relative} must reject staging before a pool can connect`)
  }
  const serialMigrationModules = [
    'crm/api/server/atendimento/professionalIdentityMigration.js',
    'crm/api/server/atendimento/writeSafetyMigration.js',
    'crm/api/server/atendimento/commercialContactMigration.js',
    'crm/api/server/atendimento/commercialContactRolloutMigration.js',
    'crm/api/server/atendimento/clientIdentityMaterializationMigration.js',
    'crm/api/server/atendimento/commercialActionLedgerMigration.js',
    'crm/api/server/atendimento/commercialDataQualityMigration.js',
    'crm/api/server/clientes/sourceOperationsMigration.js',
    'crm/api/server/atendimento/identityReviewMigration.js',
    'crm/api/server/atendimento/identityClusterWorkspaceMigration.js',
    'crm/api/server/clinical/clinicalApprovalMigration.js',
    'crm/api/server/atendimento/commercialOperationsMigration.js',
    'crm/api/server/atendimento/commercialAnalyticsMigration.js',
    'crm/api/server/atendimento/commercialCanaryMigration.js',
    'crm/api/server/atendimento/commercialAssistedCommunicationMigration.js',
  ]
  for (const relative of serialMigrationModules) {
    const migrationSource = read(relative)
    assert.equal((migrationSource.match(/\bpool\.connect\(\)/g) || []).length, 2, `${relative} must use one client for each apply and rollback path`)
    assert.equal((migrationSource.match(/\bclient\.release\(\)/g) || []).length, 2, `${relative} must release the client in both paths`)
    assert.doesNotMatch(migrationSource, /\bpool\.query\(/, `${relative} must not open an unbounded pool query path`)
    assert.doesNotMatch(migrationSource, /Promise\.all(?:Settled)?\(/, `${relative} must keep migration queries serial`)
  }
  assert.match(lockdown, /readonly DB_NAME='skincos_staging'/)
  assert.match(lockdown, /readonly APP_ROLE='skincos_staging_crm_app'/)
  assert.match(lockdown, /\/usr\/bin\/sudo -n -u postgres \/usr\/bin\/psql/)
  assert.match(lockdown, /has_table_privilege\('skincos_staging_crm_app', c\.oid, 'INSERT'\)/)
  assert.match(lockdown, /has_column_privilege\('skincos_staging_crm_app', c\.oid, a\.attname, 'UPDATE'\)/)
  assert.match(lockdown, /has_sequence_privilege\('skincos_staging_crm_app', c\.oid, 'USAGE'\)/)
  assert.match(lockdown, /pg_has_role\('skincos_staging_crm_app', candidate\.oid, 'SET'\)/)
  assert.match(lockdown, /p\.prosecdef/)
  assert.match(lockdown, /nosuperuser nocreatedb nocreaterole noreplication nobypassrls noinherit/)
  assert.match(lockdown, /revoke %I from skincos_staging_crm_app/)
  assert.match(lockdown, /revoke all privileges on schema harmonia from skincos_staging_crm_app/)
  assert.match(lockdown, /revoke all privileges on schema crm_caixa from skincos_staging_crm_app/)
  assert.match(lockdown, /n\.nspname in \('harmonia', 'crm_caixa'\)/)
  assert.match(lockdown, /c\.relkind in \('r', 'p', 'v', 'm', 'f'\)/)
  assert.match(lockdown, /pii_harmonia_read=false pii_caixa_source_read=false/)

  assert.match(control, /readonly CONTROL_FILE='\/etc\/skincos\/atendimento-staging\/module-control\.json'/)
  assert.match(control, /^#!\/usr\/bin\/bash -p/m)
  assert.match(control, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(control, /run_sudo_clean\(\)/)
  assert.match(control, /\/usr\/bin\/env -i/)
  assert.match(control, /readonly BACKUP_ROOT='\/var\/backups\/skincos\/clientes\/staging-control'/)
  assert.match(control, /commercialContactWritesEnabled":false/)
  assert.match(control, /dry_run=true/)
  assert.doesNotMatch(control, /^#!\/usr\/bin\/env bash/m)
  assert.doesNotMatch(control, /command -v/)
  assert.match(backup, /^#!\/usr\/bin\/bash -p/m)
  assert.match(backup, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(backup, /run_postgres_dump_clean\(\)/)
  assert.match(backup, /\/usr\/bin\/env -i/)
  assert.match(backup, /umask 077/)
  assert.match(backup, /run_sudo_clean \/usr\/bin\/install -d -m 0700 -o root -g root "\$BACKUP_DIR"/)
  assert.match(backup, /PENDING_OUTPUT="\$\(run_sudo_clean \/usr\/bin\/mktemp "\$BACKUP_DIR\/\$STAMP-clientes-staging-preapply\.XXXXXX\.dump\.partial"\)"/)
  assert.match(backup, /OUTPUT="\$\{PENDING_OUTPUT%\.partial\}"/)
  assert.match(backup, /Pending backup path was not generated from the fixed contract/)
  assert.match(backup, /Backup output path was not generated from the fixed contract/)
  assert.match(backup, /run_postgres_dump_clean --format=custom --no-owner --no-privileges --dbname="\$DATABASE" > "\$PENDING_OUTPUT"/)
  assert.doesNotMatch(backup, /--file=/, 'postgres must not receive a root-private backup pathname')
  assert.doesNotMatch(backup, /chown postgres:postgres/, 'postgres must never own a staging rollback artifact')
  assert.doesNotMatch(backup, /install -d -m 0750 -o root -g postgres/, 'the final backup directory must be root-private')
  assert.doesNotMatch(backup, /(?:install -d|chmod|chown)\b[^\n]*\/var\/backups\/skincos(?:\/clientes)?(?:[\s"']|$)/, 'backup ancestors must remain inaccessible to postgres')
  assert.match(backup, /\/usr\/bin\/test -O "\$PENDING_OUTPUT"/)
  assert.match(backup, /run_sudo_clean \/usr\/bin\/chmod 0600 "\$PENDING_OUTPUT"/)
  assert.match(backup, /run_sudo_clean \/usr\/bin\/test -s "\$PENDING_OUTPUT"/)
  assert.match(backup, /backup_metadata="\$\(run_sudo_clean \/usr\/bin\/stat -c '%U:%G:%a' "\$PENDING_OUTPUT"\)"/)
  assert.ok(backup.indexOf('/usr/bin/chmod 0600 "$PENDING_OUTPUT"') < backup.indexOf('run_postgres_dump_clean --format=custom'), 'the root-only spool must be 0600 before pg_dump starts')
  assert.match(backup, /backup_metadata="\$\(run_sudo_clean \/usr\/bin\/stat -c '%U:%G:%a' "\$OUTPUT"\)"/)
  assert.match(backup, /run_sudo_clean \/usr\/bin\/ln -- "\$PENDING_OUTPUT" "\$OUTPUT"/)
  assert.ok(backup.indexOf('run_postgres_dump_clean --format=custom') < backup.indexOf('/usr/bin/ln -- "$PENDING_OUTPUT" "$OUTPUT"'), 'the final path must be linked only after pg_dump completes')
  assert.ok(backup.indexOf("trap '' HUP INT TERM\nrun_sudo_clean /usr/bin/ln -- \"$PENDING_OUTPUT\" \"$OUTPUT\"\noutput_created=1") >= 0, 'trappable stops must not split publication from cleanup ownership')
  assert.ok(backup.indexOf('/usr/bin/ln -- "$PENDING_OUTPUT" "$OUTPUT"') < backup.lastIndexOf('/usr/bin/rm -f -- "$PENDING_OUTPUT"'), 'the completed dump must be atomically linked before its pending name is removed')
  assert.doesNotMatch(backup, /\/usr\/bin\/ln\s+(?:-[^\n]*f|--force)\b/, 'the final hard link must never overwrite an existing backup')
  assert.doesNotMatch(backup, /\/usr\/bin\/(?:mv|cp)\b/, 'publication must be a hard link, not a replaceable copy or rename')
  assert.match(backup, /private=true unique=true/)
  assert.match(backup, /trap cleanup_partial_output EXIT/)
  assert.match(backup, /if \[\[ "\$pending_created" == '1' \]\]; then\s+run_sudo_clean \/usr\/bin\/rm -f -- "\$PENDING_OUTPUT"/)
  assert.match(backup, /if \[\[ "\$output_created" == '1' \]\]; then\s+run_sudo_clean \/usr\/bin\/rm -f -- "\$OUTPUT"/)
  assert.ok(backup.indexOf('run_postgres_dump_clean --format=custom') < backup.indexOf("trap '' HUP INT TERM"), 'a dump failure must occur before any final publication attempt')
  assert.ok(backup.indexOf("trap '' HUP INT TERM") < backup.indexOf('output_created=1'), 'only a successfully linked output is eligible for final cleanup')
  assert.doesNotMatch(backup, /^#!\/usr\/bin\/env bash/m)
  assert.doesNotMatch(backup, /command -v/)
  assert.match(installer, /CONTROL_VALIDATOR="\$SOURCE_ROOT\/crm\/api\/scripts\/validate-atendimento-staging-control\.mjs"/)
  assert.match(installer, /RUNTIME_GRANT_LOCKDOWN="\$SOURCE_ROOT\/scripts\/lockdown-atendimento-staging-runtime\.sh"/)
  assert.match(installer, /CONTROL_FILE="\$CONFIG_ROOT\/atendimento-staging\/module-control\.json"/)
  assert.match(installer, /\"\$CONTROL_VALIDATOR\" --release-sha "\$RELEASE_SHA"/)
  assert.match(installer, /\"\$RELEASE_VALIDATOR\" --source-root "\$SOURCE_ROOT" --release-sha "\$RELEASE_SHA" --target staging/)
  assert.match(installer, /\"\$RUNTIME_GRANT_LOCKDOWN\" --dry-run/)
  assert.match(installer, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(installer, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(installer, /mktemp -d \/tmp\/atendimento-staging-unit\.XXXXXX/)
  assert.match(installer, /readonly SERVICE='crm-atendimento-staging\.service'/)
  assert.match(installer, /\/usr\/bin\/systemd-analyze verify/)
  assert.match(installer, /run_sudo_clean \/usr\/bin\/sed/)
  assert.match(installer, /\/usr\/bin\/systemctl enable "\$SERVICE"/)
  assert.match(installer, /\/usr\/bin\/systemctl restart "\$SERVICE"/)
  assert.match(installer, /unit_backup='none'/)
  assert.match(installer, /run_sudo_clean \/usr\/bin\/mktemp "\$BACKUP_ROOT\/\$\{stamp\}-crm-atendimento-staging\.XXXXXX\.service"/)
  assert.match(installer, /Unit backup path was not generated from the fixed unique contract/)
  assert.match(installer, /unit_backup_metadata="\$\(run_sudo_clean \/usr\/bin\/stat -c '%U:%G:%a' "\$unit_backup_path"\)"/)
  assert.match(installer, /run_sudo_clean \/usr\/bin\/cmp -s "\$UNIT_DEST\/\$SERVICE" "\$unit_backup_path"/)
  assert.match(installer, /unit_backup_committed=1/)
  assert.doesNotMatch(installer, /enable --now crm-atendimento-staging\.service/)
  assert.match(unit, /Environment=CRM_MODULE_CONTROL_FILE=__CONFIG_ROOT__\/atendimento-staging\/module-control\.json/)
  assert.match(control, /CONTROL_BACKUP_PATH="\$\(run_sudo_clean \/usr\/bin\/mktemp "\$BACKUP_ROOT\/\$\{stamp\}-module-control\.XXXXXX\.json"\)"/)
  assert.match(control, /Control backup path was not generated from the fixed unique contract/)
  assert.match(control, /control_backup_metadata="\$\(run_sudo_clean \/usr\/bin\/stat -c '%U:%G:%a' "\$CONTROL_BACKUP_PATH"\)"/)
  assert.match(control, /run_sudo_clean \/usr\/bin\/cmp -s "\$CONTROL_FILE" "\$CONTROL_BACKUP_PATH"/)
  assert.match(control, /CONTROL_BACKUP_COMMITTED=1/)
  assert.match(control, /control_backup=%s/)

  assert.match(rollback, /^#!\/usr\/bin\/bash -p/m)
  assert.match(rollback, /readonly UNIT_BACKUP_ROOT='\/var\/backups\/skincos\/clientes\/staging'/)
  assert.match(rollback, /readonly CONTROL_BACKUP_ROOT='\/var\/backups\/skincos\/clientes\/staging-control'/)
  assert.match(rollback, /--unit-backup must be a fixed unique staging unit backup basename/)
  assert.match(rollback, /--control-backup must be a fixed unique staging control backup basename/)
  assert.match(rollback, /--target staging/)
  assert.match(rollback, /CONTROL_BACKUP_VALIDATOR="\$SOURCE_ROOT\/crm\/api\/scripts\/validate-atendimento-staging-rollback-control\.mjs"/)
  assert.match(rollback, /\/usr\/bin\/cmp -s "\$rendered" "\$UNIT_BACKUP"/)
  assert.match(rollback, /control_state=maintenance/)
  assert.match(rollback, /\/usr\/bin\/systemctl restart "\$SERVICE"/)
  assert.match(rollback, /shared_restart=false/)
  assert.doesNotMatch(rollback, /systemctl\s+(?:restart|stop|start)\s+(?:crm\.service|crm-jobs\.service|orb\.service|cloudflare-runtime\.service)/)
  assert.doesNotMatch(rollback, /^\s*(?:source|\.)\s+[^\n]+/m)
  assert.doesNotMatch(rollback, /^\s*eval\s+/m)
  assert.match(rollbackControl, /STAGING_CONTROL_BACKUP_ROOT = '\/var\/backups\/skincos\/clientes\/staging-control'/)
  assert.match(rollbackControl, /const BACKUP_NAME = \/\^\[0-9\]\{8\}T\[0-9\]\{6\}Z-module-control\\\.\[A-Za-z0-9\]\{6\}\\\.json\$\//)
  assert.match(rollbackControl, /ATENDIMENTO_STAGING_ROLLBACK_CONTROL_NOT_MAINTENANCE/)

  assert.match(retiredTunnel, /retired=true dedicated_staging_tunnel_required=true shared_restart=false/)
  assert.doesNotMatch(retiredTunnel, /CLOUDFLARED_CONFIG_PATH|ATENDIMENTO_STAGING_HOSTNAME|ATENDIMENTO_STAGING_SERVICE/)
  assert.doesNotMatch(retiredTunnel, /cloudflare-runtime\.service|systemctl/)
})

test('production database contract has a separate read-only app role without raw contact access', () => {
  const provision = read('scripts/provision-atendimento-production-readonly.sh')
  const lockdown = read('scripts/lockdown-atendimento-production-runtime.sh')
  const installer = read('scripts/runtime/install-atendimento-production-service.sh')
  const prepare = read('scripts/runtime/prepare-atendimento-production-release.sh')
  const control = read('scripts/set-atendimento-production-readonly-control.sh')
  const validation = read('scripts/validate-atendimento-production-readonly.sh')
  const smoke = read('crm/api/scripts/atendimento-production-signed-smoke.mjs')
  assert.match(provision, /DB_NAME='skincos_clientes_production'/)
  assert.match(provision, /MIGRATOR_ROLE='skincos_clientes_migrator_login'/)
  assert.match(provision, /APP_ROLE='skincos_clientes_ro'/)
  assert.match(provision, /default_transaction_read_only = on/)
  assert.match(provision, /alter default privileges for role \$MIGRATOR_ROLE/)
  assert.match(provision, /^#!\/usr\/bin\/bash -p/m)
  assert.match(provision, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(provision, /Production provisioning requires the isolated runtime to be inactive/)
  assert.match(provision, /run_sudo_clean \/usr\/bin\/mktemp "\$BACKUP_ROOT\/\$stamp-\$DB_NAME-preapply\.XXXXXX\.dump"/)
  assert.match(provision, /Backup output path was not generated from the fixed contract/)
  assert.match(provision, /chown postgres:postgres "\$backup"/)
  assert.match(provision, /chown root:root "\$backup"/)
  assert.match(provision, /trap cleanup_partial_artifacts EXIT/)
  assert.match(provision, /mktemp \/tmp\/atendimento-production-app-env\.XXXXXX/)
  assert.match(provision, /mktemp \/tmp\/atendimento-production-control\.XXXXXX/)
  assert.match(provision, /RUNTIME_GRANT_LOCKDOWN=.*lockdown-atendimento-production-runtime\.sh/)
  assert.match(provision, /run_sudo_clean \/usr\/bin\/bash -p "\$RUNTIME_GRANT_LOCKDOWN" --apply/)
  assert.doesNotMatch(provision, /harmonia\.contacts/)
  assert.doesNotMatch(provision, /phone_raw/)
  assert.doesNotMatch(provision, /grant .*insert/i)

  assert.match(lockdown, /DB_NAME='skincos_clientes_production'/)
  assert.match(lockdown, /APP_ROLE='skincos_clientes_ro'/)
  assert.match(lockdown, /^#!\/usr\/bin\/bash -p/m)
  assert.match(lockdown, /n\.nspname in \('harmonia', 'crm_caixa'\)/)
  assert.match(lockdown, /c\.relkind in \('r', 'p', 'v', 'm', 'f'\)/)
  assert.match(lockdown, /has_column_privilege\('skincos_clientes_ro', c\.oid, a\.attname, 'SELECT'\)/)
  assert.match(lockdown, /revoke all privileges on schema harmonia from skincos_clientes_ro/)
  assert.match(lockdown, /revoke all privileges on schema crm_caixa from skincos_clientes_ro/)
  assert.match(lockdown, /production_runtime_grants_read_only=true/)

  assert.match(installer, /^#!\/usr\/bin\/bash -p/m)
  assert.match(installer, /CONTROL_VALIDATOR=.*validate-atendimento-production-control\.mjs/)
  assert.match(installer, /"\$CONTROL_VALIDATOR" --release-sha "\$RELEASE_SHA"/)
  assert.match(installer, /RUNTIME_GRANT_LOCKDOWN=.*lockdown-atendimento-production-runtime\.sh/)
  assert.match(installer, /"\$RUNTIME_GRANT_LOCKDOWN" --dry-run/)
  assert.match(installer, /"\$RUNTIME_GRANT_LOCKDOWN" --apply/)
  assert.match(installer, /mktemp -d \/tmp\/atendimento-production-unit\.XXXXXX/)
  assert.match(installer, /systemctl enable "\$SERVICE"/)
  assert.match(installer, /systemctl restart "\$SERVICE"/)
  assert.doesNotMatch(installer, /systemctl enable --now/)

  assert.match(prepare, /^#!\/usr\/bin\/bash -p/m)
  assert.match(prepare, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(prepare, /mktemp \/tmp\/atendimento-production-manifest\.XXXXXX/)
  assert.match(control, /^#!\/usr\/bin\/bash -p/m)
  assert.match(control, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(control, /mktemp \/tmp\/atendimento-production-control\.XXXXXX/)
  assert.match(validation, /RUNTIME_GRANT_LOCKDOWN=.*lockdown-atendimento-production-runtime\.sh/)
  assert.match(validation, /CONTROL_VALIDATOR=.*validate-atendimento-production-control\.mjs/)
  assert.match(validation, /"\$CONTROL_VALIDATOR" --release-sha "\$RELEASE_SHA"/)
  assert.match(validation, /"\$RUNTIME_GRANT_LOCKDOWN" --dry-run/)
  assert.match(validation, /WorkingDirectory=\$RELEASE_ROOT/)
  assert.match(validation, /--noproxy '\*'/)
  assert.match(smoke, /commercialReadsDisabled: firstRead\.response\.status === 503/)
  assert.match(smoke, /COMMERCIAL_READS_DISABLED/)
  assert.doesNotMatch(smoke, /replayRejected/)
})

test('release, rollback and tunnel paths are immutable, fixed and isolated', () => {
  const release = read('scripts/runtime/prepare-atendimento-production-release.sh')
  const rollback = read('scripts/runtime/rollback-atendimento-production.sh')
  const tunnel = read('scripts/runtime/install-atendimento-production-tunnel.sh')
  const dns = read('scripts/runtime/route-atendimento-production-dns.sh')
  assert.match(release, /readonly RELEASE_BASE='\/opt\/skincos\/releases'/)
  assert.match(release, /readonly SOURCE_ROOT="\$RELEASE_BASE\/\$RELEASE_SHA\/source"/)
  assert.match(rollback, /readonly CONTROL_WRITER="\$SOURCE_ROOT\/scripts\/set-atendimento-production-readonly-control\.sh"/)
  assert.match(rollback, /shared_restart=false/)
  assert.match(tunnel, /readonly HOSTNAME='crm-atendimento\.skincos\.com\.br'/)
  assert.match(tunnel, /CREDENTIALS_FILE="\$CONFIG_DIR\/\$TUNNEL_ID\.json"/)
  assert.match(dns, /dns_change=false/)
  assert.match(read('ops/runtime/units/cloudflare-atendimento-production.service'), /ExecStart=\/usr\/bin\/cloudflared/)
})

test('production validation invokes only loopback health plus the fixed signed smoke', () => {
  const validation = read('scripts/validate-atendimento-production-readonly.sh')
  assert.match(validation, /http:\/\/127\.0\.0\.1:\$PORT\/health/)
  assert.match(validation, /atendimento-production-signed-smoke\.mjs/)
  assert.match(validation, /skincos_clientes_ro/)
  assert.doesNotMatch(validation, /^\s*(?:source|\.)\s+[^\n]+/m)
  assert.doesNotMatch(validation, /curl[^\n]*https?:\/\/(?!127\.0\.0\.1)/)
})

test('staging validation attests only the fixed loopback runtime and strict staging control', () => {
  const validation = read('scripts/validate-atendimento-staging-readonly.sh')
  const smoke = read('crm/api/scripts/atendimento-staging-signed-smoke.mjs')
  assert.match(validation, /readonly PORT='8111'/)
  assert.match(validation, /readonly CONTROL_FILE='\/etc\/skincos\/atendimento-staging\/module-control\.json'/)
  assert.match(validation, /readonly RELEASE_ROOT="\$RELEASE_BASE\/\$RELEASE_SHA\/source"/)
  assert.match(validation, /CONTROL_VALIDATOR="\$RELEASE_ROOT\/crm\/api\/scripts\/validate-atendimento-staging-control\.mjs"/)
  assert.match(validation, /RUNTIME_GRANT_LOCKDOWN="\$RELEASE_ROOT\/scripts\/lockdown-atendimento-staging-runtime\.sh"/)
  assert.match(validation, /SMOKE="\$RELEASE_ROOT\/crm\/api\/scripts\/atendimento-staging-signed-smoke\.mjs"/)
  assert.match(validation, /"\$SMOKE" --expected-release-sha "\$RELEASE_SHA"/)
  assert.match(validation, /\"\$RUNTIME_GRANT_LOCKDOWN\" --dry-run/)
  assert.match(validation, /RELEASE_VALIDATOR="\$RELEASE_ROOT\/crm\/api\/scripts\/validate-atendimento-release\.mjs"/)
  assert.match(validation, /"\$RELEASE_VALIDATOR" --source-root "\$RELEASE_ROOT" --release-sha "\$RELEASE_SHA" --target staging/)
  assert.match(validation, /\/usr\/bin\/cmp -s "\$rendered" "\$UNIT_FILE"/)
  assert.match(validation, /run_sudo_clean \/usr\/bin\/sed/)
  assert.match(validation, /\/proc\/\$main_pid\/cmdline/)
  assert.match(validation, /--noproxy '\*'/)
  assert.match(validation, /http:\/\/127\.0\.0\.1:\$PORT\/health/)
  assert.match(validation, /loopback_health=true signed_smoke=true unit_attested=true process_attested=true/)
  assert.doesNotMatch(validation, /crm-atendimento-staging\.skincos\.com\.br|crm\.skincos\.com\.br|cloudflare-runtime\.service\s+(?:restart|stop|start)/)
  assert.doesNotMatch(validation, /^\s*(?:source|\.)\s+[^\n]+/m)
  assert.doesNotMatch(validation, /^\s*eval\s+/m)
  assert.match(smoke, /ENV_FILE = '\/etc\/skincos\/crm-atendimento-staging\.env'/)
  assert.match(smoke, /BASE_URL = 'http:\/\/127\.0\.0\.1:8111'/)
  assert.match(smoke, /SIGNATURE_PROBE_PATH = '\/api\/atendimento\/__staging-smoke__\/signature-replay'/)
  assert.match(smoke, /WRITE_PROBE_PATH = '\/api\/atendimento\/__staging-smoke__\/write-guard'/)
  assert.match(smoke, /replayRejected: replayProbe\.response\.status === 401/)
  assert.match(smoke, /writeRejected: writeProbe\.response\.status === 405/)
  assert.doesNotMatch(smoke, /crm-clientes-production-readonly\.env|\/commercial\//)
  assert.doesNotMatch(smoke, /https?:\/\/(?!127\.0\.0\.1:8111)/)
})
