import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

function assertNoDynamicShell(relative) {
  const text = read(relative)
  assert.doesNotMatch(text, /^\s*(?:source|\.)\s+[^\n]+/m, `${relative} must not load an env file as shell code`)
  assert.doesNotMatch(text, /^\s*eval\s+/m, `${relative} must not evaluate data as shell`)
  assert.doesNotMatch(text, /^\s*(?:exec\s+)?bash\s+-c\b/m, `${relative} must not create a shell command string`)
}

test('isolated Clientes unit starts only the dedicated read-only entrypoint', () => {
  const unit = read('ops/runtime/units/crm-atendimento-production.service')
  assert.match(unit, /Description=.*Clientes.*read-only/)
  assert.match(unit, /EnvironmentFile=-__CONFIG_ROOT__\/crm-clientes-production-readonly\.env/)
  assert.match(unit, /UnsetEnvironment=.*NODE_OPTIONS.*LD_PRELOAD/)
  assert.match(unit, /Environment=CRM_DOMAIN=atendimento/)
  assert.match(unit, /Environment=CRM_ATENDIMENTO_READ_ONLY=true/)
  assert.match(unit, /Environment=CRM_ATENDIMENTO_COMMERCIAL_WRITES_ENABLED=false/)
  assert.match(unit, /Environment=HARMONIA_WORKER_ENABLED=false/)
  assert.match(unit, /ExecStart=\/usr\/bin\/node __REPO_ROOT__\/crm\/api\/server\/atendimentoRuntime\.js/)
  assert.doesNotMatch(unit, /ExecStart=.*server\.js/)
  assert.doesNotMatch(unit, /ExecStart=.*bash/)
  assert.doesNotMatch(unit, /crm\.service/)
})

test('dedicated runtime cannot import the shared HTTP process or a worker', () => {
  const runtime = read('crm/api/server/atendimentoRuntime.js')
  assert.match(runtime, /createIsolatedAtendimentoRuntime/)
  assert.match(runtime, /\/internal\/readiness/)
  assert.match(runtime, /app\.get\('\/internal\/readiness', limitInternal/)
  assert.match(runtime, /app\.get\('\/internal\/metrics', limitInternal/)
  assert.match(runtime, /INTERNAL_RATE_LIMIT_MAX_REQUESTS = 60/)
  assert.match(runtime, /READ_ONLY_RUNTIME/)
  assert.doesNotMatch(runtime, /from '\.\/server\.js'/)
  assert.doesNotMatch(runtime, /from ['"].*\/workers\//)
  assert.doesNotMatch(runtime, /from ['"].*harmonia\/worker/)
})

test('native scripts parse fixed configuration without dynamic shell evaluation', () => {
  for (const relative of [
    'scripts/run-atendimento-staging-migration.sh',
    'scripts/lockdown-atendimento-staging-runtime.sh',
    'scripts/refresh-atendimento-staging-quality.sh',
    'scripts/backup-atendimento-staging.sh',
    'scripts/provision-atendimento-staging.sh',
    'scripts/set-atendimento-staging-control.sh',
    'scripts/runtime/prepare-atendimento-staging-release.sh',
    'scripts/runtime/add-atendimento-staging-tunnel-route.sh',
    'scripts/runtime/install-atendimento-staging-service.sh',
    'scripts/provision-atendimento-production-readonly.sh',
    'scripts/lockdown-atendimento-production-runtime.sh',
    'scripts/set-atendimento-production-readonly-control.sh',
    'scripts/runtime/install-atendimento-production-service.sh',
    'scripts/runtime/install-atendimento-production-tunnel.sh',
    'scripts/runtime/route-atendimento-production-dns.sh',
    'scripts/runtime/prepare-atendimento-production-release.sh',
    'scripts/runtime/rollback-atendimento-production.sh',
    'scripts/validate-atendimento-staging-readonly.sh',
    'scripts/validate-atendimento-production-readonly.sh',
  ]) assertNoDynamicShell(relative)

  const migration = read('crm/api/scripts/run-atendimento-staging-migration.mjs')
  const stagingMigration = read('scripts/run-atendimento-staging-migration.sh')
  assert.match(migration, /MIGRATOR_ENV_FILE = '\/etc\/skincos\/crm-atendimento-staging-migrator\.env'/)
  assert.match(migration, /readLiteralEnvironment/)
  assert.doesNotMatch(migration, /process\.env\.DATABASE_URL/)
  assert.match(stagingMigration, /--release-sha/)
  assert.match(stagingMigration, /\/opt\/skincos\/releases\/\$RELEASE_SHA\/source/)
  assert.match(stagingMigration, /validate-atendimento-release\.mjs/)
  assert.doesNotMatch(stagingMigration, /ROOT_DIR=.*BASH_SOURCE/)

  const qualityRefresh = read('crm/api/scripts/run-atendimento-staging-quality-refresh.mjs')
  assert.match(qualityRefresh, /MIGRATOR_ENV_FILE = '\/etc\/skincos\/crm-atendimento-staging-migrator\.env'/)
  assert.match(qualityRefresh, /readLiteralEnvironment/)
  assert.doesNotMatch(qualityRefresh, /process\.env\.DATABASE_URL\s*\|\|/)
})

test('staging release, control and application role remain fixed and read-only', () => {
  const release = read('scripts/runtime/prepare-atendimento-staging-release.sh')
  const provision = read('scripts/provision-atendimento-staging.sh')
  const control = read('scripts/set-atendimento-staging-control.sh')
  const backup = read('scripts/backup-atendimento-staging.sh')
  const stagingMigration = read('scripts/run-atendimento-staging-migration.sh')
  const lockdown = read('scripts/lockdown-atendimento-staging-runtime.sh')
  const installer = read('scripts/runtime/install-atendimento-staging-service.sh')
  const unit = read('ops/runtime/units/crm-atendimento-staging.service')
  const retiredTunnel = read('scripts/runtime/add-atendimento-staging-tunnel-route.sh')

  assert.match(release, /readonly RELEASE_BASE='\/opt\/skincos\/releases'/)
  assert.match(release, /readonly NPM_CACHE='\/var\/lib\/skincos-runtime\/cache\/crm-api'/)
  assert.match(release, /^#!\/usr\/bin\/bash -p/m)
  assert.match(release, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(release, /run_sudo_clean\(\)/)
  assert.match(release, /run_skincos_npm\(\)/)
  assert.match(release, /git_clean\(\)/)
  assert.match(release, /resolve_checkout_git_dir\(\)/)
  assert.match(release, /readonly VERIFIED_GIT_DIR="\$\(resolve_checkout_git_dir\)"/)
  assert.match(release, /"GIT_DIR=\$VERIFIED_GIT_DIR" "GIT_WORK_TREE=\$ROOT_DIR"/)
  assert.match(release, /\/usr\/bin\/env -i/)
  assert.match(release, /\/usr\/bin\/git -c "safe\.directory=\$ROOT_DIR"/)
  assert.match(release, /git_clean archive --format=tar/)
  assert.match(release, /run_sudo_clean \/usr\/bin\/tar/)
  assert.match(release, /run_skincos_npm --prefix/)
  assert.match(release, /assert_release_targets\(\)/)
  assert.match(release, /--predecessor-sha/)
  assert.match(release, /Release SHA must equal the fetched origin\/main commit/)
  assert.match(release, /merge-base --is-ancestor/)
  assert.match(release, /\.skincos-release-lineage\.json/)
  assert.match(release, /run_sudo_clean \/usr\/bin\/rm -rf -- "\$STAGING"/)
  assert.doesNotMatch(release, /SKINCOS_RELEASE_BASE|CRM_NPM_CACHE/)
  assert.doesNotMatch(release, /^#!\/usr\/bin\/env bash/m)
  assert.doesNotMatch(release, /command -v git|command -v npm/)

  assert.match(provision, /readonly CONTROL_DIR="\$CONFIG_DIR\/atendimento-staging"/)
  assert.match(provision, /readonly SERVICE='crm-atendimento-staging\.service'/)
  assert.match(provision, /Staging provisioning requires the isolated runtime to be inactive/)
  assert.match(provision, /run_postgres_clean\(\)/)
  assert.match(provision, /random_hex\(\)/)
  assert.match(provision, /\\set app_password/)
  assert.doesNotMatch(provision, /--set=app_password|--set=migrator_password/)
  assert.match(provision, /readonly BACKUP_ROOT='\/var\/backups\/skincos\/clientes\/staging-control'/)
  assert.match(provision, /ATENDIMENTO_READINESS_TOKEN=\$readiness_token/)
  assert.match(provision, /"state":"maintenance"/)
  assert.match(provision, /"readOnly":true,"commercialContactWritesEnabled":false,"syntheticOnly":true/)
  assert.match(provision, /alter role \$APP_ROLE set default_transaction_read_only = on/)
  assert.match(provision, /revoke all privileges on database \$DB_NAME from \$APP_ROLE/)
  assert.match(provision, /revoke all privileges on all tables in schema crm_atendimento, crm_caixa, crm_sessions, harmonia from \$APP_ROLE/)
  assert.match(provision, /revoke all privileges on all sequences in schema crm_atendimento, crm_caixa, crm_sessions, harmonia from \$APP_ROLE/)
  assert.match(provision, /grant select on all tables in schema crm_atendimento, crm_sessions to \$APP_ROLE/)
  assert.doesNotMatch(provision, /grant select on all tables in schema [^\n]*crm_caixa to \$APP_ROLE/)
  assert.match(provision, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(provision, /mktemp \/tmp\/atendimento-staging-app-env\.XXXXXX/)
  assert.match(provision, /mktemp \/tmp\/atendimento-staging-migrator-env\.XXXXXX/)
  assert.match(provision, /mktemp \/tmp\/atendimento-staging-control\.XXXXXX/)
  assert.doesNotMatch(provision, /grant select on all tables in schema [^\n]*harmonia to \$APP_ROLE/)
  assert.doesNotMatch(provision, /grant select, insert, update, delete on all tables in schema [^\n]+ to \$APP_ROLE/)
  assert.doesNotMatch(provision, /grant usage, select, update on all sequences in schema [^\n]+ to \$APP_ROLE/)
  assert.doesNotMatch(provision, /CRM_API_PORT=8109/)

  assert.match(stagingMigration, /RUNTIME_GRANT_LOCKDOWN="\$RELEASE_ROOT\/scripts\/lockdown-atendimento-staging-runtime\.sh"/)
  assert.match(stagingMigration, /run_sudo_clean \/usr\/bin\/bash -p "\$RUNTIME_GRANT_LOCKDOWN" --apply/)
  assert.match(stagingMigration, /\/usr\/bin\/env -i "PATH=\$SAFE_PATH"/)
  assert.match(stagingMigration, /Staging migration requires maintenance control state/)
  assert.match(stagingMigration, /\/usr\/bin\/systemctl is-active --quiet "\$SERVICE"/)
  assert.match(stagingMigration, /run_sudo_clean \/usr\/bin\/bash -p "\$RUNTIME_GRANT_LOCKDOWN" --dry-run >\/dev\/null/)
  assert.match(stagingMigration, /LOCKDOWN_REQUIRED=1/)
  assert.match(stagingMigration, /trap seal_staging_runtime_grants EXIT/)
  assert.match(stagingMigration, /trap 'exit 129' HUP/)
  assert.match(stagingMigration, /trap 'exit 130' INT/)
  assert.match(stagingMigration, /trap 'exit 143' TERM/)
  assert.match(stagingMigration, /trap '' HUP INT TERM/)
  assert.match(stagingMigration, /keeping the isolated service ineligible/)
  assert.match(lockdown, /readonly DB_NAME='skincos_staging'/)
  assert.match(lockdown, /readonly APP_ROLE='skincos_staging_crm_app'/)
  assert.match(lockdown, /\/usr\/bin\/sudo -n -u postgres \/usr\/bin\/psql/)
  assert.match(lockdown, /has_table_privilege\('skincos_staging_crm_app', c\.oid, 'INSERT'\)/)
  assert.match(lockdown, /has_column_privilege\('skincos_staging_crm_app', c\.oid, a\.attname, 'UPDATE'\)/)
  assert.match(lockdown, /has_sequence_privilege\('skincos_staging_crm_app', c\.oid, 'USAGE'\)/)
  assert.match(lockdown, /pg_has_role\('skincos_staging_crm_app', candidate\.oid, 'SET'\)/)
  assert.match(lockdown, /p\.prosecdef/)
  assert.match(lockdown, /nosuperuser nocreatedb nocreaterole noreplication nobypassrls noinherit/)
  assert.match(lockdown, /revoke %I from skincos_staging_crm_app/)
  assert.match(lockdown, /revoke all privileges on schema harmonia from skincos_staging_crm_app/)
  assert.match(lockdown, /revoke all privileges on schema crm_caixa from skincos_staging_crm_app/)
  assert.match(lockdown, /n\.nspname in \('harmonia', 'crm_caixa'\)/)
  assert.match(lockdown, /c\.relkind in \('r', 'p', 'v', 'm', 'f'\)/)
  assert.match(lockdown, /pii_harmonia_read=false pii_caixa_source_read=false/)

  assert.match(control, /readonly CONTROL_FILE='\/etc\/skincos\/atendimento-staging\/module-control\.json'/)
  assert.match(control, /^#!\/usr\/bin\/bash -p/m)
  assert.match(control, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(control, /run_sudo_clean\(\)/)
  assert.match(control, /\/usr\/bin\/env -i/)
  assert.match(control, /readonly BACKUP_ROOT='\/var\/backups\/skincos\/clientes\/staging-control'/)
  assert.match(control, /commercialContactWritesEnabled":false/)
  assert.match(control, /dry_run=true/)
  assert.doesNotMatch(control, /^#!\/usr\/bin\/env bash/m)
  assert.doesNotMatch(control, /command -v/)
  assert.match(backup, /^#!\/usr\/bin\/bash -p/m)
  assert.match(backup, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(backup, /run_postgres_dump_clean\(\)/)
  assert.match(backup, /\/usr\/bin\/env -i/)
  assert.match(backup, /run_sudo_clean \/usr\/bin\/mktemp "\$BACKUP_DIR\/\$STAMP-clientes-staging-preapply\.XXXXXX\.dump"/)
  assert.match(backup, /Backup output path was not generated from the fixed contract/)
  assert.match(backup, /chown postgres:postgres "\$OUTPUT"/)
  assert.match(backup, /chown root:root "\$OUTPUT"/)
  assert.match(backup, /trap cleanup_partial_output EXIT/)
  assert.match(backup, /output_created=1/)
  assert.match(backup, /run_sudo_clean \/usr\/bin\/rm -f -- "\$OUTPUT"/)
  assert.doesNotMatch(backup, /^#!\/usr\/bin\/env bash/m)
  assert.doesNotMatch(backup, /command -v/)
  assert.match(installer, /CONTROL_VALIDATOR="\$SOURCE_ROOT\/crm\/api\/scripts\/validate-atendimento-staging-control\.mjs"/)
  assert.match(installer, /RUNTIME_GRANT_LOCKDOWN="\$SOURCE_ROOT\/scripts\/lockdown-atendimento-staging-runtime\.sh"/)
  assert.match(installer, /CONTROL_FILE="\$CONFIG_ROOT\/atendimento-staging\/module-control\.json"/)
  assert.match(installer, /\"\$CONTROL_VALIDATOR\" --release-sha "\$RELEASE_SHA"/)
  assert.match(installer, /\"\$RUNTIME_GRANT_LOCKDOWN\" --dry-run/)
  assert.match(installer, /readonly SAFE_PATH='\/usr\/sbin:\/usr\/bin:\/sbin:\/bin'/)
  assert.match(installer, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(installer, /mktemp -d \/tmp\/atendimento-staging-unit\.XXXXXX/)
  assert.match(installer, /readonly SERVICE='crm-atendimento-staging\.service'/)
  assert.match(installer, /\/usr\/bin\/systemd-analyze verify/)
  assert.match(installer, /\/usr\/bin\/systemctl enable "\$SERVICE"/)
  assert.match(installer, /\/usr\/bin\/systemctl restart "\$SERVICE"/)
  assert.doesNotMatch(installer, /enable --now crm-atendimento-staging\.service/)
  assert.match(unit, /Environment=CRM_MODULE_CONTROL_FILE=__CONFIG_ROOT__\/atendimento-staging\/module-control\.json/)

  assert.match(retiredTunnel, /retired=true dedicated_staging_tunnel_required=true shared_restart=false/)
  assert.doesNotMatch(retiredTunnel, /CLOUDFLARED_CONFIG_PATH|ATENDIMENTO_STAGING_HOSTNAME|ATENDIMENTO_STAGING_SERVICE/)
  assert.doesNotMatch(retiredTunnel, /cloudflare-runtime\.service|systemctl/)
})

test('production database contract has a separate read-only app role without raw contact access', () => {
  const provision = read('scripts/provision-atendimento-production-readonly.sh')
  const lockdown = read('scripts/lockdown-atendimento-production-runtime.sh')
  const installer = read('scripts/runtime/install-atendimento-production-service.sh')
  const prepare = read('scripts/runtime/prepare-atendimento-production-release.sh')
  const control = read('scripts/set-atendimento-production-readonly-control.sh')
  const validation = read('scripts/validate-atendimento-production-readonly.sh')
  const smoke = read('crm/api/scripts/atendimento-production-signed-smoke.mjs')
  assert.match(provision, /DB_NAME='skincos_clientes_production'/)
  assert.match(provision, /MIGRATOR_ROLE='skincos_clientes_migrator_login'/)
  assert.match(provision, /APP_ROLE='skincos_clientes_ro'/)
  assert.match(provision, /default_transaction_read_only = on/)
  assert.match(provision, /alter default privileges for role \$MIGRATOR_ROLE/)
  assert.match(provision, /^#!\/usr\/bin\/bash -p/m)
  assert.match(provision, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(provision, /Production provisioning requires the isolated runtime to be inactive/)
  assert.match(provision, /run_sudo_clean \/usr\/bin\/mktemp "\$BACKUP_ROOT\/\$stamp-\$DB_NAME-preapply\.XXXXXX\.dump"/)
  assert.match(provision, /Backup output path was not generated from the fixed contract/)
  assert.match(provision, /chown postgres:postgres "\$backup"/)
  assert.match(provision, /chown root:root "\$backup"/)
  assert.match(provision, /trap cleanup_partial_artifacts EXIT/)
  assert.match(provision, /mktemp \/tmp\/atendimento-production-app-env\.XXXXXX/)
  assert.match(provision, /mktemp \/tmp\/atendimento-production-control\.XXXXXX/)
  assert.match(provision, /RUNTIME_GRANT_LOCKDOWN=.*lockdown-atendimento-production-runtime\.sh/)
  assert.match(provision, /run_sudo_clean \/usr\/bin\/bash -p "\$RUNTIME_GRANT_LOCKDOWN" --apply/)
  assert.doesNotMatch(provision, /harmonia\.contacts/)
  assert.doesNotMatch(provision, /phone_raw/)
  assert.doesNotMatch(provision, /grant .*insert/i)

  assert.match(lockdown, /DB_NAME='skincos_clientes_production'/)
  assert.match(lockdown, /APP_ROLE='skincos_clientes_ro'/)
  assert.match(lockdown, /^#!\/usr\/bin\/bash -p/m)
  assert.match(lockdown, /n\.nspname in \('harmonia', 'crm_caixa'\)/)
  assert.match(lockdown, /c\.relkind in \('r', 'p', 'v', 'm', 'f'\)/)
  assert.match(lockdown, /has_column_privilege\('skincos_clientes_ro', c\.oid, a\.attname, 'SELECT'\)/)
  assert.match(lockdown, /revoke all privileges on schema harmonia from skincos_clientes_ro/)
  assert.match(lockdown, /revoke all privileges on schema crm_caixa from skincos_clientes_ro/)
  assert.match(lockdown, /production_runtime_grants_read_only=true/)

  assert.match(installer, /^#!\/usr\/bin\/bash -p/m)
  assert.match(installer, /CONTROL_VALIDATOR=.*validate-atendimento-production-control\.mjs/)
  assert.match(installer, /"\$CONTROL_VALIDATOR" --release-sha "\$RELEASE_SHA"/)
  assert.match(installer, /RUNTIME_GRANT_LOCKDOWN=.*lockdown-atendimento-production-runtime\.sh/)
  assert.match(installer, /"\$RUNTIME_GRANT_LOCKDOWN" --dry-run/)
  assert.match(installer, /"\$RUNTIME_GRANT_LOCKDOWN" --apply/)
  assert.match(installer, /mktemp -d \/tmp\/atendimento-production-unit\.XXXXXX/)
  assert.match(installer, /systemctl enable "\$SERVICE"/)
  assert.match(installer, /systemctl restart "\$SERVICE"/)
  assert.doesNotMatch(installer, /systemctl enable --now/)

  assert.match(prepare, /^#!\/usr\/bin\/bash -p/m)
  assert.match(prepare, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(prepare, /mktemp \/tmp\/atendimento-production-manifest\.XXXXXX/)
  assert.match(control, /^#!\/usr\/bin\/bash -p/m)
  assert.match(control, /unset BASH_ENV ENV CDPATH GLOBIGNORE TMPDIR TMP TEMP/)
  assert.match(control, /mktemp \/tmp\/atendimento-production-control\.XXXXXX/)
  assert.match(validation, /RUNTIME_GRANT_LOCKDOWN=.*lockdown-atendimento-production-runtime\.sh/)
  assert.match(validation, /CONTROL_VALIDATOR=.*validate-atendimento-production-control\.mjs/)
  assert.match(validation, /"\$CONTROL_VALIDATOR" --release-sha "\$RELEASE_SHA"/)
  assert.match(validation, /"\$RUNTIME_GRANT_LOCKDOWN" --dry-run/)
  assert.match(validation, /WorkingDirectory=\$RELEASE_ROOT/)
  assert.match(validation, /--noproxy '\*'/)
  assert.match(smoke, /commercialReadsDisabled: firstRead\.response\.status === 503/)
  assert.match(smoke, /COMMERCIAL_READS_DISABLED/)
  assert.doesNotMatch(smoke, /replayRejected/)
})

test('release, rollback and tunnel paths are immutable, fixed and isolated', () => {
  const release = read('scripts/runtime/prepare-atendimento-production-release.sh')
  const rollback = read('scripts/runtime/rollback-atendimento-production.sh')
  const tunnel = read('scripts/runtime/install-atendimento-production-tunnel.sh')
  const dns = read('scripts/runtime/route-atendimento-production-dns.sh')
  assert.match(release, /readonly RELEASE_BASE='\/opt\/skincos\/releases'/)
  assert.match(release, /readonly SOURCE_ROOT="\$RELEASE_BASE\/\$RELEASE_SHA\/source"/)
  assert.match(rollback, /readonly CONTROL_WRITER="\$SOURCE_ROOT\/scripts\/set-atendimento-production-readonly-control\.sh"/)
  assert.match(rollback, /shared_restart=false/)
  assert.match(tunnel, /readonly HOSTNAME='crm-atendimento\.skincos\.com\.br'/)
  assert.match(tunnel, /CREDENTIALS_FILE="\$CONFIG_DIR\/\$TUNNEL_ID\.json"/)
  assert.match(dns, /dns_change=false/)
  assert.match(read('ops/runtime/units/cloudflare-atendimento-production.service'), /ExecStart=\/usr\/bin\/cloudflared/)
})

test('production validation invokes only loopback health plus the fixed signed smoke', () => {
  const validation = read('scripts/validate-atendimento-production-readonly.sh')
  assert.match(validation, /http:\/\/127\.0\.0\.1:\$PORT\/health/)
  assert.match(validation, /atendimento-production-signed-smoke\.mjs/)
  assert.match(validation, /skincos_clientes_ro/)
  assert.doesNotMatch(validation, /^\s*(?:source|\.)\s+[^\n]+/m)
  assert.doesNotMatch(validation, /curl[^\n]*https?:\/\/(?!127\.0\.0\.1)/)
})

test('staging validation attests only the fixed loopback runtime and strict staging control', () => {
  const validation = read('scripts/validate-atendimento-staging-readonly.sh')
  assert.match(validation, /readonly PORT='8111'/)
  assert.match(validation, /readonly CONTROL_FILE='\/etc\/skincos\/atendimento-staging\/module-control\.json'/)
  assert.match(validation, /readonly RELEASE_ROOT="\$RELEASE_BASE\/\$RELEASE_SHA\/source"/)
  assert.match(validation, /CONTROL_VALIDATOR="\$RELEASE_ROOT\/crm\/api\/scripts\/validate-atendimento-staging-control\.mjs"/)
  assert.match(validation, /RUNTIME_GRANT_LOCKDOWN="\$RELEASE_ROOT\/scripts\/lockdown-atendimento-staging-runtime\.sh"/)
  assert.match(validation, /\"\$RUNTIME_GRANT_LOCKDOWN\" --dry-run/)
  assert.match(validation, /RELEASE_VALIDATOR="\$RELEASE_ROOT\/crm\/api\/scripts\/validate-atendimento-release\.mjs"/)
  assert.match(validation, /\/usr\/bin\/cmp -s "\$rendered" "\$UNIT_FILE"/)
  assert.match(validation, /\/proc\/\$main_pid\/cmdline/)
  assert.match(validation, /--noproxy '\*'/)
  assert.match(validation, /http:\/\/127\.0\.0\.1:\$PORT\/health/)
  assert.match(validation, /loopback_health=true unit_attested=true process_attested=true/)
  assert.doesNotMatch(validation, /crm-atendimento-staging\.skincos\.com\.br|crm\.skincos\.com\.br|cloudflare-runtime\.service\s+(?:restart|stop|start)/)
  assert.doesNotMatch(validation, /^\s*(?:source|\.)\s+[^\n]+/m)
  assert.doesNotMatch(validation, /^\s*eval\s+/m)
})
