import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

test('isolated Clientes production unit is loopback-configured and cannot broaden the shared runtime', () => {
  const unit = read('ops/runtime/units/crm-atendimento-production.service')
  assert.match(unit, /Description=.*Clientes.*read-only/)
  assert.match(unit, /EnvironmentFile=-__CONFIG_ROOT__\/crm-clientes-production-readonly\.env/)
  assert.match(unit, /ReadWritePaths=__STATE_ROOT__\/crm-atendimento-production/)
  assert.match(unit, /CRM_GRACEFUL_SHUTDOWN=true/)
  assert.match(unit, /CRM_ATENDIMENTO_ACTOR_SIGNATURE_VERSION=2/)
  assert.match(unit, /CRM_API_HOST=127\.0\.0\.1/)
  assert.match(unit, /CRM_API_PORT=8110/)
  assert.match(unit, /CRM_MODULE_CONTROL_FILE=__CONFIG_ROOT__\/atendimento-production\/module-control\.json/)
  assert.match(unit, /HARMONIA_WORKER_ENABLED=false/)
  assert.doesNotMatch(unit, /ExecStart=.*crm\.service/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /CRM_API_HOST=127\.0\.0\.1/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /skincos_clientes_production/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /skincos_clientes_migrator/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /pg_dump --format=custom/)
  assert.match(read('scripts/runtime/prepare-atendimento-production-release.sh'), /current origin\/main SHA/)
  assert.match(read('scripts/runtime/prepare-atendimento-production-release.sh'), /predecessorSha/)
  assert.match(read('scripts/runtime/rollback-atendimento-production.sh'), /target.*production/)
  assert.match(read('scripts/runtime/rollback-atendimento-production.sh'), /readOnly.*true/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /CRM_ATENDIMENTO_READ_ONLY=true/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /CRM_ATENDIMENTO_CLIENTES_ONLY=true/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /CRM_ATENDIMENTO_EXPECTED_DATABASE=\$DB_NAME/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /default_transaction_read_only = on/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /create role \$OWNER_ROLE nologin/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /revoke create, temporary on database \$DB_NAME from \$APP_ROLE/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /grant usage, create on schema .*harmonia/)
  assert.match(read('scripts/provision-atendimento-production-readonly.sh'), /grant select \(phone_raw, opted_out_at\) on table harmonia\.contacts/)
  assert.match(read('scripts/runtime/manage-native-runtime.sh'), /crm-atendimento-production\.service/)
  assert.match(read('ops/runtime/units/cloudflare-atendimento-production.service'), /crm-atendimento-production\.service/)
  assert.doesNotMatch(read('scripts/runtime/install-atendimento-production-tunnel.sh'), /cloudflare-runtime\.service.*restart|crm\.service.*restart/)
  assert.match(read('scripts/runtime/route-atendimento-production-dns.sh'), /crm-atendimento\.skincos\.com\.br/)
  assert.doesNotMatch(read('scripts/runtime/route-atendimento-production-dns.sh'), /cloudflared[^\n]*--overwrite-dns/)
  const server = read('crm/api/server.js')
  assert.doesNotMatch(server, /startHarmoniaWorker/)
  assert.match(server, /HARMONIA_WORKER_MUST_RUN_IN_CONTINUOUS_WORKER_PROCESS/)
  assert.match(server, /IS_ATENDIMENTO_RUNTIME/)
  assert.match(server, /ATENDIMENTO_RUNTIME_SCOPE/)
  assert.match(server, /if \(!IS_ATENDIMENTO_RUNTIME\)/)
})

test('production validation proves the API and database write barriers without sending customer data', () => {
  const validation = read('scripts/validate-atendimento-production-readonly.sh')
  assert.match(validation, /writeRejected/)
  assert.match(validation, /commercial\/actions/)
  assert.match(validation, /skincos_clientes_ro/)
  assert.match(validation, /global_client_identities/)
  assert.match(validation, /crm_caixa\.sales/)
  assert.match(validation, /harmonia\.contacts/)
  assert.match(validation, /has_column_privilege/)
  assert.match(validation, /commercial_contact_writes_enabled/)
  assert.match(validation, /canary_count/)
  assert.match(validation, /PUBLIC_HEALTH_URL/)
  assert.match(validation, /crm\.service/)
  assert.match(validation, /crm-jobs\.service/)
  assert.match(validation, /cloudflare-runtime\.service/)
  assert.match(validation, /orb\.service/)
  assert.match(read('scripts/crm/atendimento-production-signed-smoke.mjs'), /replayRejected/)
  assert.match(read('scripts/crm/atendimento-production-signed-smoke.mjs'), /expected-release-sha/)
})

test('production control refuses active state without an immutable full SHA', () => {
  const control = read('scripts/set-atendimento-production-readonly-control.sh')
  assert.match(control, /STATE.*active/)
  assert.match(control, /release-sha.*full lowercase SHA/)
  assert.match(control, /state.*disabled\|maintenance\|active/)
})
