export {
    CAMPAIGN_PARAM_KEYS,
    type CampaignParamKey,
    type CampaignParams,
    type StoredAttribution,
    type TrackingContext,
    buildTrackingContextFromBrowser,
    campaignParamsForEvent,
    deriveFbcFromFbclid,
    extractCampaignParamsFromSearchParams,
    persistAttributionSnapshot,
    persistCampaignParams,
    readCurrentCampaignParams,
    readFacebookBrowserId,
    readFacebookClickIdCookie,
    readPersistedAttribution,
} from "@/lib/attribution";
