#!/usr/bin/env bash

if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  _runtime_paths_source="${BASH_SOURCE[0]}"
else
  _runtime_paths_source="$0"
fi

_runtime_paths_lib_dir="$(cd "$(dirname "$_runtime_paths_source")" && pwd)"
_runtime_paths_script_dir="$(cd "$_runtime_paths_lib_dir/.." && pwd)"
_runtime_paths_repo_root="$(cd "$_runtime_paths_script_dir/.." && pwd)"

N8N_ROOT="${N8N_ROOT:-$_runtime_paths_repo_root}"
N8N_RUNTIME_HOME="${N8N_RUNTIME_HOME:-/var/lib/skincos-runtime/orb}"
CLOUDFLARED_HOME="${CLOUDFLARED_HOME:-/etc/skincos/cloudflare/orb}"
N8N_ENV_FILE="${N8N_ENV_FILE:-/etc/skincos/orb.env}"
N8N_BUSINESS_ENV_FILE="${N8N_BUSINESS_ENV_FILE:-/etc/skincos/orb-business.env}"
N8N_HEALTH_DIR="${N8N_HEALTH_DIR:-$N8N_RUNTIME_HOME/health}"
N8N_LOG_DIR="${N8N_LOG_DIR:-/var/log/skincos/orb}"
N8N_TMP_DIR="${N8N_TMP_DIR:-/tmp}"
N8N_DATA_HOME="${N8N_DATA_HOME:-$N8N_RUNTIME_HOME/n8n-home}"
N8N_STATE_HOME="${N8N_STATE_HOME:-$N8N_DATA_HOME/.n8n}"
N8N_STORAGE_PATH="${N8N_STORAGE_PATH:-$N8N_STATE_HOME/storage}"
N8N_BINARY_DATA_DIR="${N8N_BINARY_DATA_DIR:-$N8N_STORAGE_PATH}"
N8N_DB_PATH="${N8N_DB_PATH:-$N8N_STATE_HOME/database.sqlite}"
N8N_CONFIG_PATH="${N8N_CONFIG_PATH:-$N8N_STATE_HOME/config}"
N8N_NODES_DIR="${N8N_NODES_DIR:-$N8N_STATE_HOME/nodes}"
N8N_LEGACY_CONFIG_PATH="${N8N_LEGACY_CONFIG_PATH:-$N8N_DATA_HOME/config}"
N8N_LEGACY_NODES_DIR="${N8N_LEGACY_NODES_DIR:-$N8N_DATA_HOME/nodes}"
EVOLUTION_ENV_FILE="${EVOLUTION_ENV_FILE:-/etc/skincos/messaging-whatsapp.env}"
EVOLUTION_INSTANCES_DIR="${EVOLUTION_INSTANCES_DIR:-/var/lib/skincos-runtime/messaging-whatsapp/instances}"
EVOLUTION_STORE_DIR="${EVOLUTION_STORE_DIR:-/var/lib/skincos-runtime/messaging-whatsapp/store}"
SKINCOS_N8N_SERVICE="${SKINCOS_N8N_SERVICE:-orb.service}"
SKINCOS_ORB_PROXY_SERVICE="${SKINCOS_ORB_PROXY_SERVICE:-orb-proxy.service}"
SKINCOS_CLOUDFLARED_ORB_SERVICE="${SKINCOS_CLOUDFLARED_ORB_SERVICE:-cloudflare-orb.service}"
SKINCOS_EVOLUTION_SERVICE="${SKINCOS_EVOLUTION_SERVICE:-messaging-whatsapp.service}"
SKINCOS_BACKUP_SERVICE="${SKINCOS_BACKUP_SERVICE:-orb-backup.service}"

export N8N_ROOT N8N_RUNTIME_HOME CLOUDFLARED_HOME N8N_ENV_FILE N8N_BUSINESS_ENV_FILE
export N8N_HEALTH_DIR N8N_LOG_DIR N8N_TMP_DIR N8N_STORAGE_PATH N8N_BINARY_DATA_DIR
export N8N_DATA_HOME N8N_STATE_HOME N8N_DB_PATH N8N_CONFIG_PATH N8N_NODES_DIR
export N8N_LEGACY_CONFIG_PATH N8N_LEGACY_NODES_DIR EVOLUTION_ENV_FILE
export EVOLUTION_INSTANCES_DIR EVOLUTION_STORE_DIR SKINCOS_N8N_SERVICE
export SKINCOS_ORB_PROXY_SERVICE SKINCOS_CLOUDFLARED_ORB_SERVICE
export SKINCOS_EVOLUTION_SERVICE SKINCOS_BACKUP_SERVICE
