-- Music Composition Studio: additive, inactive-by-default ledger schema.
create schema if not exists music_studio;
create table if not exists music_studio.music_productions (production_id text primary key, composition_id text not null, status text not null, revision integer not null default 1, input_hash text not null, constitution_hash text, dry_run boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists music_studio.music_constitutions (constitution_id uuid primary key default gen_random_uuid(), production_id text not null references music_studio.music_productions(production_id), revision integer not null, lock_hash text not null, payload jsonb not null, created_at timestamptz not null default now(), unique (production_id, revision), unique (production_id, lock_hash));
create table if not exists music_studio.music_jobs (job_key text primary key, production_id text not null references music_studio.music_productions(production_id), module text not null, component_id text not null, revision integer not null, input_hash text not null, status text not null, provider text, model text, attempt integer not null default 0, cost numeric(12,4) not null default 0, error_code text, error_message text, lineage jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (production_id, module, component_id, revision, input_hash));
create table if not exists music_studio.music_artifacts (artifact_id text primary key, production_id text not null references music_studio.music_productions(production_id), uri text not null, checksum text not null, kind text not null, status text not null default 'COMPLETED', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique (production_id, checksum));
create table if not exists music_studio.music_dependencies (production_id text not null references music_studio.music_productions(production_id), component_id text not null, depends_on_component_id text not null, dependency_hash text not null, created_at timestamptz not null default now(), primary key (production_id, component_id, depends_on_component_id));
create table if not exists music_studio.music_candidates (candidate_id text primary key, production_id text not null references music_studio.music_productions(production_id), candidate_type text not null, score numeric(6,4), payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_composition_dna (composition_dna_id text primary key, production_id text not null references music_studio.music_productions(production_id), compatibility_score numeric(6,4) not null, payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_sections (section_id text primary key, production_id text not null references music_studio.music_productions(production_id), section_type text not null, payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_stems (stem_job_id text primary key, production_id text not null references music_studio.music_productions(production_id), section_id text not null, role text not null, artifact_id text, payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_arrangements (arrangement_id text primary key, production_id text not null references music_studio.music_productions(production_id), lock_hash text not null, payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_mix_versions (mix_id text primary key, production_id text not null references music_studio.music_productions(production_id), lock_hash text not null, payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_master_versions (master_id text primary key, production_id text not null references music_studio.music_productions(production_id), payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_qa_reports (qa_id uuid primary key default gen_random_uuid(), production_id text not null references music_studio.music_productions(production_id), decision text not null, report jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_provider_events (event_id text primary key, production_id text not null references music_studio.music_productions(production_id), job_key text, provider text not null, payload jsonb not null, created_at timestamptz not null default now());
create table if not exists music_studio.music_cost_events (event_id text primary key, production_id text not null references music_studio.music_productions(production_id), provider text not null, amount numeric(12,4) not null, currency text not null default 'USD', payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists music_studio.music_reference_analyses (analysis_id uuid primary key default gen_random_uuid(), production_id text not null references music_studio.music_productions(production_id), reference_id text not null, rights_status text not null, analysis jsonb not null, created_at timestamptz not null default now(), unique (production_id, reference_id));
