[CmdletBinding()]
param([string]$RuntimeDirectory = 'C:\CodexRuntime\operator\admin\skincos\observability', [string]$TaskName = 'SkincosObservabilityProbe', [int]$DashboardPort = 18799)
$ErrorActionPreference = 'Stop'; $sourceRoot = Split-Path -Parent $PSScriptRoot; $bin = Join-Path $RuntimeDirectory 'bin'; $isElevated=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator); New-Item -ItemType Directory -Force -Path $bin | Out-Null
function Stop-ExistingSupervisor {
  $supervisorName = 'Start-SkincosObservabilitySupervisor.ps1'
  foreach ($process in Get-CimInstance Win32_Process | Where-Object { $_.Name -eq 'powershell.exe' -and $_.CommandLine -and $_.CommandLine -like "*$supervisorName*" -and $_.CommandLine -like "*$RuntimeDirectory*" }) {
    try { Stop-Process -Id $process.ProcessId -Force -ErrorAction Stop } catch {}
  }
}
Copy-Item -LiteralPath (Join-Path $sourceRoot 'catalog.json') -Destination (Join-Path $RuntimeDirectory 'catalog.json') -Force
foreach($name in @('Invoke-SkincosObservability.ps1','Serve-SkincosObservabilityDashboard.ps1','Watch-SkincosObservability.ps1','Start-SkincosObservabilitySupervisor.ps1')) { Copy-Item -LiteralPath (Join-Path $PSScriptRoot $name) -Destination (Join-Path $bin $name) -Force }
if($isElevated){ if (-not [System.Diagnostics.EventLog]::SourceExists('SkincosObservability')) { New-EventLog -LogName Application -Source 'SkincosObservability' }; & icacls $RuntimeDirectory /grant '*S-1-5-18:(OI)(CI)F' /T /C | Out-Null }
$monitorAction=New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$(Join-Path $bin 'Invoke-SkincosObservability.ps1')`" -CatalogPath `"$(Join-Path $RuntimeDirectory 'catalog.json')`" -StateDirectory `"$RuntimeDirectory`""
$dashboardAction=New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$(Join-Path $bin 'Serve-SkincosObservabilityDashboard.ps1')`" -StateDirectory `"$RuntimeDirectory`" -Port $DashboardPort"
$watchdogAction=New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$(Join-Path $bin 'Watch-SkincosObservability.ps1')`" -StateDirectory `"$RuntimeDirectory`" -CatalogPath `"$(Join-Path $RuntimeDirectory 'catalog.json')`" -DashboardTaskName SkincosObservabilityDashboard"
if($isElevated){$principal=New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest; $lifecycleTrigger=New-ScheduledTaskTrigger -AtStartup; $executionMode='system'}else{$principal=New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Highest; $lifecycleTrigger=New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME; $executionMode='operator-interactive'}
$period=New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval (New-TimeSpan -Minutes 1) -RepetitionDuration (New-TimeSpan -Days 3650); $settings=New-ScheduledTaskSettingsSet -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 2) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) -MultipleInstances IgnoreNew
try{
  Register-ScheduledTask -TaskName $TaskName -Action $monitorAction -Trigger @($lifecycleTrigger,$period) -Principal $principal -Settings $settings -Description "SKINCOS external synthetic monitor ($executionMode); staging and production reads only." -Force -ErrorAction Stop | Out-Null
  $dashboardSettings=New-ScheduledTaskSettingsSet -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) -MultipleInstances IgnoreNew; Register-ScheduledTask -TaskName 'SkincosObservabilityDashboard' -Action $dashboardAction -Trigger $lifecycleTrigger -Principal $principal -Settings $dashboardSettings -Description "Local loopback dashboard and monitor health endpoint ($executionMode)." -Force -ErrorAction Stop | Out-Null
  $watchdogTrigger=New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval (New-TimeSpan -Minutes 2) -RepetitionDuration (New-TimeSpan -Days 3650); Register-ScheduledTask -TaskName 'SkincosObservabilityWatchdog' -Action $watchdogAction -Trigger @($lifecycleTrigger,$watchdogTrigger) -Principal $principal -Settings $settings -Description "Independent watchdog for external monitor freshness and dashboard restart ($executionMode)." -Force -ErrorAction Stop | Out-Null
  Remove-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'SkincosObservability' -ErrorAction SilentlyContinue
  Stop-ExistingSupervisor
  Start-ScheduledTask -TaskName $TaskName -ErrorAction Stop; Start-ScheduledTask -TaskName 'SkincosObservabilityDashboard' -ErrorAction Stop; Start-ScheduledTask -TaskName 'SkincosObservabilityWatchdog' -ErrorAction Stop; $taskNames=@($TaskName,'SkincosObservabilityDashboard','SkincosObservabilityWatchdog')
}catch{
  foreach($registeredTask in @($TaskName,'SkincosObservabilityDashboard','SkincosObservabilityWatchdog')){try{Unregister-ScheduledTask -TaskName $registeredTask -Confirm:$false -ErrorAction Stop}catch{}}
  $executionMode='operator-run-key'; $supervisor=Join-Path $bin 'Start-SkincosObservabilitySupervisor.ps1'; $command="powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$supervisor`" -StateDirectory `"$RuntimeDirectory`" -CatalogPath `"$(Join-Path $RuntimeDirectory 'catalog.json')`" -DashboardPort $DashboardPort"; New-Item -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Force|Out-Null; Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'SkincosObservability' -Value $command; Stop-ExistingSupervisor; Start-Process -FilePath powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$supervisor`" -StateDirectory `"$RuntimeDirectory`" -CatalogPath `"$(Join-Path $RuntimeDirectory 'catalog.json')`" -DashboardPort $DashboardPort" -WindowStyle Hidden; $taskNames=@()
}
Set-Content -LiteralPath (Join-Path $RuntimeDirectory 'dashboard-url.txt') -Value "http://127.0.0.1:$DashboardPort/" -NoNewline
@{execution_mode=$executionMode;installed_at=[DateTime]::UtcNow.ToString('o');task_names=$taskNames;startup='automatic'}|ConvertTo-Json|Set-Content -LiteralPath (Join-Path $RuntimeDirectory 'installation.json'); Write-Output "Installed external observability ($executionMode). State: $RuntimeDirectory"
