import React from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/card'
import { Button } from '@/button'
import { Input } from '@/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/select'
import { financeApi, minorUnitsFromDisplay, type FinanceBootstrap } from '@/financeApi'

const today = new Date().toISOString().slice(0, 10)
const monthStart = `${today.slice(0, 8)}01`
const money = (minor = 0) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(minor || 0) / 100)

export function FinanceModule() {
  const [boot, setBoot] = React.useState<FinanceBootstrap | null>(null)
  const [scopeId, setScopeId] = React.useState('')
  const [data, setData] = React.useState<any>(null)
  const [error, setError] = React.useState('')
  const [loading, setLoading] = React.useState(true)
  const [from, setFrom] = React.useState(monthStart)
  const [to, setTo] = React.useState(today)
  const [accountName, setAccountName] = React.useState('')
  const [csvFile, setCsvFile] = React.useState<File | null>(null)
  const [movement, setMovement] = React.useState({ type: 'income', accountId: '', destinationAccountId: '', categoryId: '', description: '', amount: '' })
  const [categoryName, setCategoryName] = React.useState('')
  const [categoryDirection, setCategoryDirection] = React.useState<'income' | 'expense'>('expense')
  const [payeeName, setPayeeName] = React.useState('')
  const [actionError, setActionError] = React.useState('')
  const [importBatchId, setImportBatchId] = React.useState('')

  const refresh = React.useCallback(async (nextScope = scopeId) => {
    if (!nextScope) return
    setLoading(true); setError('')
    try {
      const [overview, accounts, movements, categories, payees] = await Promise.all([financeApi.overview(nextScope, from, to), financeApi.accounts(nextScope), financeApi.movements(nextScope), financeApi.categories(nextScope), financeApi.payees(nextScope)])
      setData({ overview, accounts: accounts.accounts || [], movements: movements.movements || [], categories: categories.categories || [], payees: payees.payees || [] })
    } catch (e: any) { setError(e?.message || 'Não foi possível carregar o Financeiro.') } finally { setLoading(false) }
  }, [from, scopeId, to])

  React.useEffect(() => { financeApi.bootstrap().then((result) => { setBoot(result); const first = result.grants?.[0]?.scope_id || ''; setScopeId(first); if (first && result.canAccess) refresh(first) }).catch((e) => { setError(e?.message || 'Não foi possível validar o acesso.'); setLoading(false) }) }, []) // bootstrap is intentionally once per mount
  React.useEffect(() => { if (boot?.canAccess && scopeId) refresh() }, [from, to, scopeId])

  if (loading && !data && !error) return <Card className="glass-card"><CardContent className="p-8 text-muted-foreground">Carregando dados financeiros…</CardContent></Card>
  if (error && !data) return <Card className="glass-card"><CardHeader><CardTitle>Financeiro indisponível</CardTitle><CardDescription>{error}</CardDescription></CardHeader><CardContent><Button onClick={() => window.location.reload()}>Tentar novamente</Button></CardContent></Card>
  if (!boot?.moduleEnabled) return <Card className="glass-card"><CardHeader><CardTitle>Financeiro ainda não está ativado</CardTitle><CardDescription>O núcleo está protegido por feature flag e não há dados expostos.</CardDescription></CardHeader></Card>
  if (!boot.canAccess || !scopeId) return <Card className="glass-card"><CardHeader><CardTitle>Sem permissão para Financeiro</CardTitle><CardDescription>Peça uma concessão explícita de escopo ao administrador.</CardDescription></CardHeader></Card>

  const runAction = async (action: () => Promise<void>) => { setActionError(''); try { await action() } catch (e: any) { setActionError(e?.message || 'Não foi possível concluir a operação.') } }
  const createAccount = () => runAction(async () => { if (!accountName.trim()) return; await financeApi.create('/accounts', scopeId, { name: accountName, type: 'bank', currency: 'BRL' }); setAccountName(''); refresh() })
  const importCsv = () => runAction(async () => { if (!csvFile) return; const csv = await csvFile.text(); const result = await financeApi.stageCsv(scopeId, csvFile.name, csv); setImportBatchId(result.batchId); setCsvFile(null) })
  const createMovement = () => runAction(async () => { const amountMinor = minorUnitsFromDisplay(movement.amount); if (!movement.accountId || !movement.description.trim() || !amountMinor || (movement.type === 'transfer' && !movement.destinationAccountId) || (movement.type !== 'transfer' && !movement.categoryId)) { setActionError('Preencha conta, categoria compatível e valor.'); return } await financeApi.create('/movements', scopeId, { ...movement, amountMinor, competenceDate: today, paidDate: today, currency: 'BRL' }); setMovement({ type: 'income', accountId: '', destinationAccountId: '', categoryId: '', description: '', amount: '' }); refresh() })
  const createNamed = (path: '/categories' | '/payees', name: string, done: () => void) => runAction(async () => { if (!name.trim()) return; await financeApi.create(path, scopeId, path === '/categories' ? { name, direction: categoryDirection } : { name }); done(); refresh() })
  return <div className="space-y-6">
    {actionError ? <Card className="border-destructive"><CardContent className="p-3 text-sm text-destructive">{actionError}</CardContent></Card> : null}
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold">Financeiro</h2><p className="text-muted-foreground">Dados reais, auditáveis e separados por contexto.</p></div><div className="flex gap-2"><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} /><Select value={scopeId} onValueChange={setScopeId}><SelectTrigger className="w-52"><SelectValue /></SelectTrigger><SelectContent>{boot.grants.map((grant) => <SelectItem key={grant.scope_id} value={grant.scope_id}>{grant.label}</SelectItem>)}</SelectContent></Select><Button onClick={() => refresh()}>Atualizar</Button></div></div>
    <div className="grid gap-4 md:grid-cols-3">{[['Entradas', data?.overview?.totals?.income, 'text-emerald-600'], ['Saídas', data?.overview?.totals?.expense, 'text-rose-600'], ['Resultado', data?.overview?.totals?.result, 'text-sky-600']].map(([label,value,color]) => <Card key={String(label)} className="glass-card"><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className={`text-2xl font-bold ${color}`}>{money(value as number)}</p></CardContent></Card>)}</div>
    <div className="grid gap-6 lg:grid-cols-2"><Card className="glass-card"><CardHeader><CardTitle>Contas financeiras</CardTitle><CardDescription>Saldo calculado por lançamentos confirmados.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={accountName} onChange={(e) => setAccountName(e.target.value)} placeholder="Nova conta" /><Button onClick={createAccount}>Adicionar</Button></div>{data?.accounts?.length ? data.accounts.map((account: any) => <div key={account.id} className="flex justify-between border-b py-2"><span>{account.name}</span><strong>{money(data.overview?.accounts?.find((item: any) => item.id === account.id)?.balance_minor ?? account.opening_balance_minor)}</strong></div>) : <p className="py-6 text-center text-muted-foreground">Nenhuma conta cadastrada neste escopo.</p>}</CardContent></Card>
    <Card className="glass-card"><CardHeader><CardTitle>Importar CSV</CardTitle><CardDescription>O arquivo entra em staging; nenhuma movimentação é criada sem revisão.</CardDescription></CardHeader><CardContent className="space-y-3"><Input type="file" accept=".csv,text/csv" onChange={(e) => setCsvFile(e.target.files?.[0] || null)} /><Button disabled={!csvFile} onClick={importCsv}>Enviar para prévia</Button>{importBatchId ? <p className="text-sm text-muted-foreground">Lote {importBatchId} em staging. A tela de mapeamento/decisão ainda não está liberada nesta versão; confirme o lote somente pela rota protegida após revisão operacional.</p> : null}<p className="text-xs text-muted-foreground">Integrações EF, MoneyWiz e Open Finance usarão este mesmo pipeline.</p></CardContent></Card></div>
    <Card className="glass-card"><CardHeader><CardTitle>Movimentações</CardTitle><CardDescription>Receitas, despesas e transferências persistidas no razão.</CardDescription></CardHeader><CardContent>{data?.movements?.length ? <div className="space-y-2">{data.movements.map((movement: any) => <div key={movement.id} className="grid grid-cols-[1fr_auto_auto] gap-3 border-b py-2 text-sm"><span>{movement.description}<small className="ml-2 text-muted-foreground">{movement.competence_date}</small></span><span>{movement.type}</span><strong>{money(movement.amount_minor)}</strong></div>)}</div> : <p className="py-8 text-center text-muted-foreground">Nenhuma movimentação no período selecionado.</p>}</CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card className="glass-card"><CardHeader><CardTitle>Novo lançamento</CardTitle><CardDescription>Cria receita, despesa ou transferência com trilha de auditoria.</CardDescription></CardHeader><CardContent className="grid gap-3"><Select value={movement.type} onValueChange={(type) => setMovement((current) => ({ ...current, type, categoryId: '' }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="income">Receita</SelectItem><SelectItem value="expense">Despesa</SelectItem><SelectItem value="transfer">Transferência</SelectItem></SelectContent></Select><Select value={movement.accountId} onValueChange={(accountId) => setMovement((current) => ({ ...current, accountId }))}><SelectTrigger><SelectValue placeholder="Conta de origem" /></SelectTrigger><SelectContent>{data.accounts.map((account: any) => <SelectItem key={account.id} value={account.id}>{account.name}</SelectItem>)}</SelectContent></Select>{movement.type !== 'transfer' ? <Select value={movement.categoryId} onValueChange={(categoryId) => setMovement((current) => ({ ...current, categoryId }))}><SelectTrigger><SelectValue placeholder="Categoria" /></SelectTrigger><SelectContent>{data.categories.filter((category: any) => category.direction === movement.type).map((category: any) => <SelectItem key={category.id} value={category.id}>{category.name}</SelectItem>)}</SelectContent></Select> : null}{movement.type === 'transfer' ? <Select value={movement.destinationAccountId} onValueChange={(destinationAccountId) => setMovement((current) => ({ ...current, destinationAccountId }))}><SelectTrigger><SelectValue placeholder="Conta de destino" /></SelectTrigger><SelectContent>{data.accounts.filter((account: any) => account.id !== movement.accountId).map((account: any) => <SelectItem key={account.id} value={account.id}>{account.name}</SelectItem>)}</SelectContent></Select> : null}<Input value={movement.description} onChange={(e) => setMovement((current) => ({ ...current, description: e.target.value }))} placeholder="Descrição" /><Input inputMode="decimal" value={movement.amount} onChange={(e) => setMovement((current) => ({ ...current, amount: e.target.value }))} placeholder="Valor (ex.: 120,50)" /><Button onClick={createMovement}>Salvar lançamento</Button></CardContent></Card>
    <Card className="glass-card"><CardHeader><CardTitle>Cadastros</CardTitle><CardDescription>Categorias e favorecidos pertencem ao escopo selecionado.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={categoryName} onChange={(e) => setCategoryName(e.target.value)} placeholder="Nova categoria" /><Select value={categoryDirection} onValueChange={(value: 'income' | 'expense') => setCategoryDirection(value)}><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="expense">Despesa</SelectItem><SelectItem value="income">Receita</SelectItem></SelectContent></Select><Button onClick={() => createNamed('/categories', categoryName, () => setCategoryName(''))}>Adicionar</Button></div><div className="flex gap-2"><Input value={payeeName} onChange={(e) => setPayeeName(e.target.value)} placeholder="Novo favorecido" /><Button onClick={() => createNamed('/payees', payeeName, () => setPayeeName(''))}>Adicionar</Button></div><p className="text-xs text-muted-foreground">{data.categories.length} categorias · {data.payees.length} favorecidos</p></CardContent></Card></div>
  </div>
}
