import React from 'react'
import { CheckCircle, WarningCircle } from '@phosphor-icons/react'
import { Button } from '@/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/dialog'
import { Input } from '@/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/table'
import { financeApi, type FinanceGrant } from '@/financeApi'

type Props = { open: boolean; onOpenChange: (value: boolean) => void; scopeId: string; grants: FinanceGrant[]; canOperate: boolean; onCompleted: () => Promise<void> }
type Lists = { accounts: any[]; categories: any[]; payees: any[] }
const fields = [{ id: 'date', label: 'Data' }, { id: 'description', label: 'Descrição' }, { id: 'amount', label: 'Valor' }, { id: 'income', label: 'Entrada' }, { id: 'expense', label: 'Saída' }, { id: 'account', label: 'Conta no arquivo' }, { id: 'category', label: 'Categoria no arquivo' }, { id: 'payee', label: 'Favorecido' }, { id: 'currency', label: 'Moeda' }, { id: 'note', label: 'Observação' }, { id: 'externalId', label: 'Identificador externo' }]

async function readCsv(file: File) {
  if (file.size > 2_000_000) throw new Error('O arquivo ultrapassa o limite seguro de 2 MB.')
  const bytes = await file.arrayBuffer(); let text = ''; let encoding = 'utf-8'
  try { text = new TextDecoder('utf-8', { fatal: true }).decode(bytes) } catch { text = new TextDecoder('windows-1252').decode(bytes); encoding = 'windows-1252' }
  if (!text.trim()) throw new Error('O arquivo está vazio.')
  return { text, encoding }
}

export function FinanceImportDialog({ open, onOpenChange, scopeId: initialScope, grants, canOperate, onCompleted }: Props) {
  const [stage, setStage] = React.useState<'file' | 'mapping' | 'review' | 'confirm' | 'result'>('file')
  const [scopeId, setScopeId] = React.useState(initialScope); const [sourceType, setSourceType] = React.useState<'generic' | 'moneywiz' | 'ef-caixa'>('generic'); const [file, setFile] = React.useState<File | null>(null); const [csv, setCsv] = React.useState(''); const [encoding, setEncoding] = React.useState('utf-8')
  const [batch, setBatch] = React.useState<any>(null); const [mapping, setMapping] = React.useState<Record<string, string>>({}); const [lists, setLists] = React.useState<Lists>({ accounts: [], categories: [], payees: [] }); const [defaults, setDefaults] = React.useState({ accountId: '', incomeCategoryId: '', expenseCategoryId: '' })
  const [busy, setBusy] = React.useState(''); const [error, setError] = React.useState(''); const [result, setResult] = React.useState<any>(null)
  React.useEffect(() => { if (open) { setScopeId(initialScope); setSourceType('generic'); setStage('file'); setFile(null); setCsv(''); setBatch(null); setError(''); setResult(null) } }, [initialScope, open])
  React.useEffect(() => { if (!open || !scopeId) return; void Promise.all([financeApi.accounts(scopeId), financeApi.categories(scopeId), financeApi.payees(scopeId)]).then(([accounts, categories, payees]) => { setLists({ accounts: accounts.accounts || [], categories: categories.categories || [], payees: payees.payees || [] }); setDefaults({ accountId: '', incomeCategoryId: '', expenseCategoryId: '' }) }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Não foi possível carregar os cadastros do escopo.')) }, [open, scopeId])
  const reload = async (batchId = batch?.id || batch?.batchId) => { const next = await financeApi.import(scopeId, batchId); setBatch(next.batch ? next : { ...next, id: batchId }); setMapping(next.batch?.mapping || mapping); return next }
  const createBatch = async () => { if (!file || !csv) return; setBusy('stage'); setError(''); try { const efCaixa = sourceType === 'ef-caixa' ? JSON.parse(csv) : undefined; const staged = await financeApi.stageCsv(scopeId, file.name, csv, { encoding, sourceType, efCaixa }); const loaded = await reload(staged.batchId); setMapping(staged.analysis?.mapping || loaded.batch?.mapping || {}); setStage('mapping') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível criar o lote.') } finally { setBusy('') } }
  const analyse = async () => { if (!batch) return; setBusy('analyse'); setError(''); try { await financeApi.importAnalyze(scopeId, batch.batch.id || batch.id, { mapping, encoding }); await reload(batch.batch.id || batch.id); setStage('review') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível analisar o arquivo.') } finally { setBusy('') } }
  const decide = async (row: any, decision: 'import' | 'skip' | 'review', transferAccountId?: string) => { if (!batch) return; setBusy(row.id); try { await financeApi.importDecision(scopeId, batch.batch.id || batch.id, { rowId: row.id, decision, transferAccountId: transferAccountId || undefined }); await reload(batch.batch.id || batch.id) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível registrar a decisão.') } finally { setBusy('') } }
  const commit = async () => { if (!batch || !defaults.accountId || !defaults.incomeCategoryId || !defaults.expenseCategoryId) { setError('Selecione conta e categorias de receita e despesa antes de confirmar.'); return } setBusy('commit'); setError(''); try { const response = await financeApi.importCommit(scopeId, batch.batch.id || batch.id, { defaultAccountId: defaults.accountId, incomeCategoryId: defaults.incomeCategoryId, expenseCategoryId: defaults.expenseCategoryId }); setResult(response); await reload(batch.batch.id || batch.id); await onCompleted(); setStage('result') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível confirmar o lote.') } finally { setBusy('') } }
  const undo = async () => { if (!batch) return; setBusy('undo'); setError(''); try { const response = await financeApi.importUndo(scopeId, batch.batch.id || batch.id, 'Desfazer importação CSV pela interface'); setResult(response); await reload(batch.batch.id || batch.id); await onCompleted() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível desfazer o lote.') } finally { setBusy('') } }
  const rows = batch?.rows || []; const summary = batch?.batch?.summary || batch?.summary || {}; const headers: string[] = batch?.batch?.headers || []
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-5xl"><DialogHeader><DialogTitle>Importar CSV financeiro</DialogTitle><DialogDescription>O arquivo, fingerprints, mapeamento, decisões e resultado ficam no lote auditável. Nada é apagado ao desfazer.</DialogDescription></DialogHeader>{error ? <p role="alert" className="rounded border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive"><WarningCircle className="mr-2 inline" size={16} />{error}</p> : null}
    <div className="flex flex-wrap gap-2 text-xs text-muted-foreground"><span>1. Arquivo</span><span>→ 2. Mapeamento</span><span>→ 3. Revisão</span><span>→ 4. Confirmação</span><span>→ 5. Resultado</span></div>
    {stage === 'file' ? <div className="grid gap-4"><label className="grid gap-1 text-sm">Origem do arquivo<Select value={sourceType} onValueChange={(value) => setSourceType(value as 'generic' | 'moneywiz' | 'ef-caixa')}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="generic">CSV genérico</SelectItem><SelectItem value="moneywiz">MoneyWiz</SelectItem><SelectItem value="ef-caixa">Caixa EF (entrega controlada)</SelectItem></SelectContent></Select></label>{sourceType === 'moneywiz' ? <p className="rounded border bg-muted/40 p-3 text-sm text-muted-foreground">Reconhece a exportação CSV de transações do MoneyWiz. Transferências ficam em revisão até confirmação; o adaptador não grava no razão.</p> : null}{sourceType === 'ef-caixa' ? <p className="rounded border bg-muted/40 p-3 text-sm text-muted-foreground">Aceita somente a entrega JSON versionada do coletor Caixa EF. A unidade precisa coincidir com o escopo; cancelamentos, estornos e taxas ficam em revisão.</p> : null}<label className="grid gap-1 text-sm">Escopo de destino<Select value={scopeId} onValueChange={setScopeId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{grants.filter((grant) => grant.kind !== 'personal' && ['operator', 'admin'].includes(grant.permission)).map((grant) => <SelectItem key={grant.scope_id} value={grant.scope_id}>{grant.label}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-1 text-sm">{sourceType === 'ef-caixa' ? 'Entrega Caixa EF (JSON)' : 'Arquivo CSV'}<Input aria-label={sourceType === 'ef-caixa' ? 'Entrega Caixa EF' : 'Arquivo CSV'} type="file" accept={sourceType === 'ef-caixa' ? '.json,application/json' : '.csv,text/csv'} onChange={(event) => { const selected = event.target.files?.[0] || null; setFile(selected); setCsv(''); setError(''); if (selected) void readCsv(selected).then(({ text, encoding: detected }) => { setCsv(text); setEncoding(detected) }).catch((cause) => setError(cause.message)) }} /></label>{file ? <p className="text-sm text-muted-foreground">{file.name} · {Math.ceil(file.size / 1024)} KB · leitura {encoding}</p> : null}</div> : null}
    {stage === 'mapping' ? <div className="grid max-h-[52vh] gap-4 overflow-y-auto pr-1"><p className="text-sm text-muted-foreground">Delimitador detectado: <strong>{batch?.batch?.delimiter || batch?.analysis?.delimiter}</strong> · formato de data: <strong>{batch?.batch?.date_format || batch?.analysis?.dateFormat}</strong>.</p><div className="grid gap-3 md:grid-cols-2">{fields.map((field) => <label key={field.id} className="grid gap-1 text-sm">{field.label}<Select value={mapping[field.id] || '__none'} onValueChange={(value) => setMapping((current) => ({ ...current, [field.id]: value === '__none' ? '' : value }))}><SelectTrigger><SelectValue placeholder="Não mapear" /></SelectTrigger><SelectContent><SelectItem value="__none">Não mapear</SelectItem>{headers.map((header) => <SelectItem key={header} value={header}>{header}</SelectItem>)}</SelectContent></Select></label>)}</div></div> : null}
    {stage === 'review' ? <div className="grid max-h-[52vh] gap-4 overflow-y-auto pr-1"><div className="grid gap-3 md:grid-cols-3"><Picker label="Conta de destino" value={defaults.accountId} onChange={(value) => setDefaults((current) => ({ ...current, accountId: value }))} items={lists.accounts} /><Picker label="Categoria padrão de receita" value={defaults.incomeCategoryId} onChange={(value) => setDefaults((current) => ({ ...current, incomeCategoryId: value }))} items={lists.categories.filter((item) => item.direction === 'income')} /><Picker label="Categoria padrão de despesa" value={defaults.expenseCategoryId} onChange={(value) => setDefaults((current) => ({ ...current, expenseCategoryId: value }))} items={lists.categories.filter((item) => item.direction === 'expense')} /></div><p className="text-sm">{summary.total || rows.length} linhas · {summary.invalid || 0} com erro · {summary.exactDuplicate || 0} duplicidade exata · {summary.probableDuplicate || 0} provável · {summary.possibleTransfer || 0} possível transferência.</p><Table><TableHeader><TableRow><TableHead>Linha</TableHead><TableHead>Descrição</TableHead><TableHead>Situação</TableHead><TableHead>Decisão</TableHead></TableRow></TableHeader><TableBody>{rows.map((row: any) => { const item = (() => { try { return JSON.parse(row.normalized_json) } catch { return null } })(); const transfer = (batch.transferCandidates || []).find((candidate: any) => candidate.row_id === row.id); return <TableRow key={row.id}><TableCell>{row.row_number}</TableCell><TableCell>{item?.description || row.error || 'Linha inválida'}<div className="text-xs text-muted-foreground">{item?.competenceDate || ''} · {item?.amountMinor || ''} minor units</div></TableCell><TableCell>{row.status === 'valid' ? 'Pronta' : row.status === 'exact_duplicate' ? 'Duplicidade exata' : row.status === 'invalid' ? 'Erro' : 'Revisar'}{transfer ? <div className="text-xs text-amber-700">Possível transferência</div> : null}</TableCell><TableCell className="space-x-2"><Button size="sm" variant={row.decision === 'import' ? 'default' : 'outline'} disabled={Boolean(busy) || row.status === 'invalid'} onClick={() => void decide(row, 'import')}>Importar</Button><Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={() => void decide(row, 'skip')}>Ignorar</Button>{transfer && lists.accounts.length ? <Select value="none" onValueChange={(value) => void decide(row, 'import', value === 'none' ? undefined : value)}><SelectTrigger className="mt-1 h-8 w-36"><SelectValue placeholder="Transferir" /></SelectTrigger><SelectContent><SelectItem value="none">Não transferir</SelectItem>{lists.accounts.filter((account) => account.id !== defaults.accountId).map((account) => <SelectItem key={account.id} value={account.id}>Transferir: {account.name}</SelectItem>)}</SelectContent></Select> : null}</TableCell></TableRow> })}</TableBody></Table></div> : null}
    {stage === 'confirm' ? <div className="space-y-3 rounded border p-4"><h3 className="font-semibold">Resumo antes da confirmação</h3><p className="text-sm">Serão criados somente lançamentos aprovados. O commit é idempotente e cada lançamento terá partida dobrada e auditoria.</p><ul className="text-sm text-muted-foreground"><li>Conta: {lists.accounts.find((item) => item.id === defaults.accountId)?.name || 'não selecionada'}</li><li>Receitas: {lists.categories.find((item) => item.id === defaults.incomeCategoryId)?.name || 'não selecionada'}</li><li>Despesas: {lists.categories.find((item) => item.id === defaults.expenseCategoryId)?.name || 'não selecionada'}</li></ul></div> : null}
    {stage === 'result' ? <div className="space-y-3 rounded border border-emerald-500/40 bg-emerald-500/5 p-4"><h3 className="flex items-center gap-2 font-semibold"><CheckCircle size={18} />Resultado auditável</h3><p className="text-sm">{result?.undone ? `${result.undone} lançamentos foram estornados por operação compensatória.` : `${result?.committed || 0} lançamentos confirmados.`}</p>{batch?.batch?.undone_at ? <p className="text-sm text-muted-foreground">O lote foi desfeito em {batch.batch.undone_at}; as evidências continuam disponíveis.</p> : <Button variant="outline" disabled={busy === 'undo'} onClick={() => void undo()}>{busy === 'undo' ? 'Desfazendo…' : 'Desfazer por estorno auditável'}</Button>}</div> : null}
    <DialogFooter>{stage !== 'file' && stage !== 'result' ? <Button variant="outline" onClick={() => setStage(stage === 'mapping' ? 'file' : stage === 'review' ? 'mapping' : 'review')}>Voltar</Button> : null}<Button variant="outline" onClick={() => onOpenChange(false)}>Fechar</Button>{stage === 'file' ? <Button disabled={!file || !csv || !canOperate || busy === 'stage'} onClick={() => void createBatch()}>{busy === 'stage' ? 'Lendo…' : 'Criar lote'}</Button> : null}{stage === 'mapping' ? <Button disabled={busy === 'analyse'} onClick={() => void analyse()}>{busy === 'analyse' ? 'Analisando…' : 'Analisar e pré-visualizar'}</Button> : null}{stage === 'review' ? <Button onClick={() => setStage('confirm')}>Revisar confirmação</Button> : null}{stage === 'confirm' ? <Button disabled={busy === 'commit'} onClick={() => void commit()}>{busy === 'commit' ? 'Confirmando…' : 'Confirmar importação'}</Button> : null}</DialogFooter>
  </DialogContent></Dialog>
}

function Picker({ label, value, onChange, items }: { label: string; value: string; onChange: (value: string) => void; items: any[] }) { return <label className="grid gap-1 text-sm">{label}<Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{items.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></label> }
