const fs = require('fs');
const path = require('path');
const { organizerInput, postingOutput } = require('./adapters');
const { validate, lockHash } = require('./lib/contracts');
const { sha256 } = require('./lib/canonical');
const { MemoryLedger } = require('./lib/ledger');
const { MockProvider } = require('./lib/providers');
const { renderStill, renderVideoFixture } = require('../services/renderer');

function baseRequest(overrides = {}) { return { schema_version: '1.0.0', production_id: 'dryrun-production', content_id: 'dryrun-content', campaign_id: 'dryrun-campaign', source_folder_id: null, output_folder_id: null, content_type: 'STATIC_SINGLE', production_tier: 'FAST', objective: 'gerar conteúdo de teste', funnel_stage: 'consideration', audience: { segment: 'fixture' }, procedure_or_topic: 'cuidados faciais', offer: {}, cta: 'Saiba mais', requested_deliverables: [{ deliverable_id: 'fixture-1', format: '9:16', usage: 'ORGANIC' }], source_assets: [], brand_assets: [], references: [], mandatory_elements: [], forbidden_elements: ['promessa garantida'], provider_policy: { mode: 'mock', mock_provider: true, allowed_providers: ['mock'], max_cost: 0, max_jobs: 20, max_revisions: 2 }, budget: { max_cost: 0 }, dry_run: true, organizer_context: { fixture: true }, ...overrides }; }

async function run(request, options = {}) {
  const normalized = organizerInput({ production_request: request });
  const ledger = new MemoryLedger(); ledger.beginProduction(normalized);
  const foundation = { schema_version: '1.0.0', production_id: normalized.production_id, commercial_facts: normalized.offer, scientific_claims: [], brand_rules: {}, compliance_rules: { forbidden: normalized.forbidden_elements }, evidence_registry: [], conflicts: [], missing_information: [], needs_review: Boolean(options.conflict) };
  validate('factualFoundation', foundation);
  const constitution = { schema_version: '1.0.0', production_id: normalized.production_id, central_thesis: normalized.procedure_or_topic, audience: normalized.audience, awareness_stage: normalized.funnel_stage, creative_angle: 'clareza e confiança', primary_emotion: 'segurança', conversion_goal: normalized.objective, message_hierarchy: [normalized.procedure_or_topic, normalized.cta], approved_claim_ids: [], prohibited_claim_ids: [], offer_facts: normalized.offer, cta: normalized.cta, tone: 'claro', mandatory_elements: normalized.mandatory_elements, forbidden_elements: normalized.forbidden_elements, brand_rules: {}, lock_hash: '', status: options.conflict ? 'NEEDS_REVIEW' : 'CONSTITUTION_LOCKED' };
  constitution.lock_hash = lockHash(constitution); validate('constitution', constitution);
  const blueprint = { schema_version: '1.0.0', production_id: normalized.production_id, constitution_hash: constitution.lock_hash, strategy: { tier: normalized.production_tier }, master_script: { duration_seconds: normalized.content_type === 'STATIC_SINGLE' ? 0 : 6 }, hook_variations: [{ id: 'hook-a', text: normalized.procedure_or_topic }], beat_map: [{ beat: 1, seconds: 0 }], visual_bible: { palette: ['#1c2230', '#d6b26e'] }, audio_bible: { route: 'mock' }, scene_manifests: [{ scene_id: 'scene-1', duration_seconds: 6, fallback: 'clean_still' }], production_plan: { dry_run: true }, prompts: [{ component: 'clean_plate', text: 'visual only; no commercial text' }], restrictions: normalized.forbidden_elements, storyboard: { ready: true, method: 'keyframe-fixture' }, lock_hash: '', status: 'BLUEPRINT_LOCKED' };
  blueprint.lock_hash = lockHash(blueprint); validate('blueprint', blueprint);
  const provider = new MockProvider(); const outputDir = options.outputDir || path.join(process.cwd(), 'output', 'ccg-dry-run', normalized.production_id); const jobInput = { production_id: normalized.production_id, module: 'CCG-40', component_id: 'deliverable-1', revision: 1, input_hash: sha256({ normalized, blueprint }), dry_run: true, provider_policy: normalized.provider_policy };
  const job = ledger.upsertJob({ ...jobInput, status: 'RUNNING' }); const providerJob = await provider.submit(jobInput); const still = renderStill({ outputDir, deliverableId: 'deliverable-1', overlays: [{ text: normalized.cta }] }); const media = normalized.content_type === 'STATIC_SINGLE' ? still : renderVideoFixture({ outputDir, deliverableId: 'deliverable-1', timeline: { duration_seconds: 6, tracks: [] } });
  ledger.recordArtifact({ artifact_id: 'artifact-1', uri: media.uri, checksum: media.checksum, status: 'APPROVED' }); ledger.upsertJob({ ...job, status: 'DONE', artifact_checksum: media.checksum, output_hash: sha256(media) });
  const qaStatus = options.blocking ? 'FAIL' : options.conflict ? 'NEEDS_REVIEW' : 'PASS'; const qa = { schema_version: '1.0.0', production_id: normalized.production_id, results: [{ category: 'factual', status: qaStatus, score: qaStatus === 'PASS' ? 100 : 30 }], status: qaStatus, blocking_issues: options.blocking ? ['claim_without_evidence'] : [], recommended_fixes: options.conflict ? ['resolver conflito comercial'] : [], score: qaStatus === 'PASS' ? 100 : 30 }; validate('qaReport', qa);
  const pkg = { schema_version: '1.0.0', production_id: normalized.production_id, content_id: normalized.content_id, status: qaStatus === 'PASS' ? 'READY_TO_PUBLISH' : qaStatus === 'FAIL' ? 'FAILED' : 'NEEDS_REVIEW', constitution_ref: { uri: `memory://${normalized.production_id}/constitution`, id: null, checksum: constitution.lock_hash, mime_type: 'application/json', metadata: {} }, blueprint_ref: { uri: `memory://${normalized.production_id}/blueprint`, id: null, checksum: blueprint.lock_hash, mime_type: 'application/json', metadata: {} }, master: { uri: media.uri, id: null, checksum: media.checksum, mime_type: media.mime_type, metadata: media }, deliverables: [{ deliverable_id: 'deliverable-1', revision: 1, content_type: normalized.content_type, usage: 'ORGANIC', format: '9:16', aspect_ratio: '9:16', duration_seconds: media.duration_seconds || null, uri: media.uri, cover_uri: still.uri, checksum: media.checksum, title: normalized.procedure_or_topic, caption: normalized.cta, description: normalized.procedure_or_topic, hashtags: [], alt_text: normalized.procedure_or_topic, ad_copy: [], qa_status: qaStatus, technical_metadata: media }], source_artifacts: [], generation_log: [{ provider: providerJob.provider, request_id: providerJob.request_id, cost: 0, dry_run: true }], qa_summary: qa, warnings: options.conflict ? ['NEEDS_REVIEW: conflito de preço/condição'] : [], posting_payload: { publish_requested: false } };
  validate('contentPackage', pkg); ledger.finishProduction(normalized.production_id, pkg.status, sha256(pkg)); return { request: normalized, factual_foundation: foundation, content_constitution: constitution, creative_blueprint: blueprint, qa_report: qa, content_package: pkg, ledger: ledger.snapshot(), posting_adapter: pkg.status === 'FAILED' ? { accepted: false, review_status: 'FAILED', publish_requested: false } : postingOutput(pkg) };
}

module.exports = { baseRequest, run };
