const strictObject = (properties, required = Object.keys(properties)) => ({ type: 'object', additionalProperties: false, properties, required });
const string = { type: 'string' };
const nullableString = { anyOf: [{ type: 'string' }, { type: 'null' }] };
const stringArray = { type: 'array', items: string };
const ref = strictObject({ uri: string, id: nullableString, checksum: nullableString, mime_type: nullableString, metadata: { type: 'object', additionalProperties: true } }, ['uri']);
const evidence = strictObject({ source_id: string, source_type: string, locator: nullableString, excerpt: nullableString, checksum: nullableString, status: { type: 'string', enum: ['APPROVED', 'PENDING', 'REJECTED'] } });
const claim = strictObject({ claim_id: string, technical_text: string, consumer_text: string, qualification: string, status: { type: 'string', enum: ['APPROVED', 'CONDITIONAL', 'PROHIBITED'] }, evidence_strength: string, source_ids: stringArray, allowed_contexts: stringArray, forbidden_contexts: stringArray });

const productionRequest = strictObject({
  schema_version: string, production_id: string, content_id: string, campaign_id: string,
  source_folder_id: nullableString, output_folder_id: nullableString,
  content_type: { type: 'string', enum: ['STATIC_SINGLE', 'CAROUSEL', 'SHORT_VIDEO', 'HYBRID'] },
  production_tier: { type: 'string', enum: ['FAST', 'STANDARD', 'PREMIUM'] }, objective: string, funnel_stage: string,
  audience: { type: 'object', additionalProperties: true }, procedure_or_topic: string,
  offer: { type: 'object', additionalProperties: true }, cta: string, requested_deliverables: { type: 'array', items: { type: 'object', additionalProperties: true } },
  source_assets: { type: 'array', items: ref }, brand_assets: { type: 'array', items: ref }, references: { type: 'array', items: ref },
  mandatory_elements: stringArray, forbidden_elements: stringArray,
  provider_policy: strictObject({ mode: { type: 'string', enum: ['mock', 'http'] }, mock_provider: { type: 'boolean' }, allowed_providers: stringArray, max_cost: { type: 'number', minimum: 0 }, max_jobs: { type: 'integer', minimum: 0 }, max_revisions: { type: 'integer', minimum: 0 } }),
  budget: { type: 'object', additionalProperties: true }, dry_run: { type: 'boolean' }, organizer_context: { type: 'object', additionalProperties: true },
}, ['schema_version', 'production_id', 'content_id', 'campaign_id', 'content_type', 'production_tier', 'objective', 'funnel_stage', 'audience', 'procedure_or_topic', 'offer', 'cta', 'requested_deliverables', 'source_assets', 'brand_assets', 'references', 'mandatory_elements', 'forbidden_elements', 'provider_policy', 'budget', 'dry_run', 'organizer_context']);

const factualFoundation = strictObject({ schema_version: string, production_id: string, commercial_facts: { type: 'object', additionalProperties: true }, scientific_claims: { type: 'array', items: claim }, brand_rules: { type: 'object', additionalProperties: true }, compliance_rules: { type: 'object', additionalProperties: true }, evidence_registry: { type: 'array', items: evidence }, conflicts: { type: 'array', items: { type: 'object', additionalProperties: true } }, missing_information: stringArray, needs_review: { type: 'boolean' } });
const constitution = strictObject({ schema_version: string, production_id: string, central_thesis: string, audience: { type: 'object', additionalProperties: true }, awareness_stage: string, creative_angle: string, primary_emotion: string, conversion_goal: string, message_hierarchy: stringArray, approved_claim_ids: stringArray, prohibited_claim_ids: stringArray, offer_facts: { type: 'object', additionalProperties: true }, cta: string, tone: string, mandatory_elements: stringArray, forbidden_elements: stringArray, brand_rules: { type: 'object', additionalProperties: true }, lock_hash: string, status: { type: 'string', enum: ['CONSTITUTION_LOCKED', 'NEEDS_REVIEW'] } });
const blueprint = strictObject({ schema_version: string, production_id: string, constitution_hash: string, strategy: { type: 'object', additionalProperties: true }, master_script: { type: 'object', additionalProperties: true }, hook_variations: { type: 'array', items: { type: 'object', additionalProperties: true } }, beat_map: { type: 'array', items: { type: 'object', additionalProperties: true } }, visual_bible: { type: 'object', additionalProperties: true }, audio_bible: { type: 'object', additionalProperties: true }, scene_manifests: { type: 'array', items: { type: 'object', additionalProperties: true } }, production_plan: { type: 'object', additionalProperties: true }, prompts: { type: 'array', items: { type: 'object', additionalProperties: true } }, restrictions: stringArray, storyboard: { type: 'object', additionalProperties: true }, lock_hash: string, status: { type: 'string', enum: ['BLUEPRINT_LOCKED', 'NEEDS_REVIEW'] } });
const manifest = strictObject({ schema_version: string, production_id: string, items: { type: 'array', items: { type: 'object', additionalProperties: true } }, version: string, input_hash: string, output_hash: string });
const qaReport = strictObject({ schema_version: string, production_id: string, results: { type: 'array', items: { type: 'object', additionalProperties: true } }, status: { type: 'string', enum: ['PASS', 'NEEDS_REVIEW', 'FAIL'] }, blocking_issues: stringArray, recommended_fixes: stringArray, score: { type: 'number', minimum: 0, maximum: 100 } });
const deliverable = strictObject({ deliverable_id: string, revision: { type: 'integer', minimum: 1 }, content_type: string, usage: { type: 'string', enum: ['ORGANIC', 'PAID'] }, format: string, aspect_ratio: string, duration_seconds: { anyOf: [{ type: 'number' }, { type: 'null' }] }, uri: string, cover_uri: nullableString, checksum: string, title: string, caption: string, description: string, hashtags: stringArray, alt_text: string, ad_copy: stringArray, qa_status: { type: 'string', enum: ['PASS', 'NEEDS_REVIEW', 'FAIL'] }, technical_metadata: { type: 'object', additionalProperties: true } });
const contentPackage = strictObject({ schema_version: string, production_id: string, content_id: string, status: { type: 'string', enum: ['READY_TO_PUBLISH', 'NEEDS_REVIEW', 'FAILED'] }, constitution_ref: ref, blueprint_ref: ref, master: ref, deliverables: { type: 'array', items: deliverable }, source_artifacts: { type: 'array', items: ref }, generation_log: { type: 'array', items: { type: 'object', additionalProperties: true } }, qa_summary: qaReport, warnings: stringArray, posting_payload: { type: 'object', additionalProperties: true } });

module.exports = { productionRequest, factualFoundation, constitution, blueprint, sceneManifest: manifest, assetManifest: manifest, audioManifest: manifest, productionManifest: manifest, timeline: manifest, qaReport, contentPackage, evidence, claim, artifact: ref, providerJob: strictObject({ job_id: string, status: string, provider: string, request_id: nullableString, input_hash: string, output_hash: nullableString, cost: { type: 'number', minimum: 0 }, attempt: { type: 'integer', minimum: 0 }, error: nullableString }), error: strictObject({ code: string, message: string, retryable: { type: 'boolean' }, blocking: { type: 'boolean' } }), revision: strictObject({ revision: { type: 'integer', minimum: 1 }, reason: string, invalidated_components: stringArray }) };
